### ISSUE TITLE
web.dom-collections.iterator polyfill added on Object iteration

### ISSUE THREAD

**Issue by igneel64** [zloirock/core-js#1003]
Hey peeps 😄 

Going through the extracted core-js polyfills for some of our code, I noticed that a large portion of `web.dom-collections.iterator` polyfills are being added, without our project depending so much on DOMCollection iterations.

Looking a bit more closely I noticed that `for...of` loops are triggering this polyfill. 
[Babel repl reproduction](https://babeljs.io/repl/#?browsers=last%202%20versions%2C%20ios_saf%20%3E%2012%2C%20Safari%20%3E%2012%2C%20%3E%201%25%2C%20not%20dead%2C%20not%20ie%20%3E%200&build=&builtIns=usage&corejs=3.6&spec=false&loose=false&code_lz=FAMwrgdgxgLglgewgAgDYIOYGkCmBPAZwAoEAjAKwEpkBvYASBAQCciokCZkBrfZBEPwqU6yMePYQCCVDgB06DEV55KwccgC-wbcGBA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=true&targets=&version=7.16.2&externalPlugins=&assumptions=%7B%7D)

Is this the expected behaviour ? If yes, the documentation of this polyfill seemed not so clear to me.

Thanks!

**Comment by zloirock** [comment]
Yes, this is expected behavior.  With statical analysis, we can't determine the type of `obj`, so we add default iterators on iteration: array iterator, string iterator, iterators of DOM collections. The rest iterators, for example, map iterator, added on an instance of related type creation. With your targets (Safari > 12), array and string iterator are not required, so added only iterators of DOM collections.

If the documentation of this is not clear for you - it's not a correct place for this, it should be documented on Babel side - you could create an issue about it here https://github.com/babel/website.
