### ISSUE TITLE
[core-js-builder] 

### ISSUE THREAD

**Issue by tomkdgun** [zloirock/core-js#1027]
core-js-builder requires old webpack version 4 ("webpack": ">=4.46.0 <5"), which has few vulnerabilities https://github.com/zloirock/core-js/blob/master/packages/core-js-builder/package.json.

It would be nice to switch to webpack 5 version free from this issues.

CVE-2021-27290
- webpack-4.46.0.tgz
  - terser-webpack-plugin-1.4.5.tgz
    - cacache-12.0.4.tgz
          :x: **ssri-6.0.2.tgz** (Vulnerable Library) - Fix Resolution: 8.0.1

CVE-2020-28469
- webpack-4.46.0.tgz
  - watchpack-1.7.5.tgz
    - watchpack-chokidar2-2.0.1.tgz
      - chokidar-2.1.8.tgz
          :x: **glob-parent-3.1.0.tgz** (Vulnerable Library) - Fix Resolution: glob-parent - 5.1.2

**Comment by zloirock** [comment]
Yes, thanks. I monitor all dependencies, so I know it. The problem is that `core-js-builder@3` should support NodeJS 8, but Webpack 5 requires NodeJS 10 - it will be a breaking change. It will be fixed only in `core-js-builder@4`, but it will be published only with other `core-js@4` infrastructure.

The best way to fix it is to publish a new Webpack 4 patch release, but they [don't want to fix even more significant issues in old branches](https://github.com/webpack/webpack/issues/14532#issuecomment-947513562).

Anyway, I don't see a way how those issues can be exploited for causing problems to `core-js-builder`.

So wait for `core-js-builder@4`.
