### ISSUE TITLE
Browser rejection hook

### ISSUE THREAD

**Issue by benjamingr** [zloirock/core-js#106]
Hey, it would be great for us if you exposed the `process` `unhandledRejection` hook event somehow to browsers, this is useful for logging errors and handling problems.

Alternatively, if you make the `isNode` check overridable.

**Comment by zloirock** [comment]
Awaiting proposals how do it w/o breaking current default behavior and adding `process` module to browser bundles for most users. Or you mean [that](https://github.com/domenic/unhandled-rejections-browser-spec)?

**Comment by benjamingr** [comment]
The problem is that it's a lot of code to run these browser events in old browsers. I think even just adding a window.onpossiblyunhandledrejection and not guaranteeing it will stay around is immensely useful.

**Comment by zloirock** [comment]
You mean simple
```js
if(isNode){
  process.emit('unhandledRejection', reason, promise);
} else if(global.onunhandledrejection){
  global.onunhandledrejection({promise: promise, reason: reason});
} else if(global.console && console.error){
  console.error('Unhandled promise rejection', reason);
}
```
?

**Comment by benjamingr** [comment]
That would work and definitely aid a ton of people in debugging.

The main use case is that we have to include a bigger library (like bluebird) if we want any form of reporting of client side errors - which are useful in order to track errors users get so we can fix them.

**Comment by zloirock** [comment]
Ok, I will add it.

**Warning**: The problem here - we can't add it to native implementations, but by idea `core-js` should use enough correct native implementation if it's available. Currently, most native implementations are buggy and `core-js` uses polyfill, but the situation will be changed. If someone wanna use this hook everywhere - he should delete `window.Promise` before inclusion `core-js`.
