### ISSUE TITLE
Plz help clarify the wordings used in the README doc

### ISSUE THREAD

**Issue by sakopqiu** [zloirock/core-js#1066]
Below is an excerpt from the current README, but it seems confusing to me.

What do you mean by "Stable ES", "web standards" ?
What is the different between "core-js/es", "core-js/stable" and "core-js/actual"?

```
// polyfill all actual features - stable ES, web standards and stage 3 ES proposals:
import "core-js/actual";
// polyfill only stable features - ES and web standards:
import "core-js/stable";
// polyfill only stable ES features:
```

**Comment by zloirock** [comment]
- `es` namespace - only stable (stage 4) ECMAScript features

**Comment by sakopqiu** [comment]
so `es` namespace does not include web standards, only the stage 4 features?

**Comment by zloirock** [comment]
Yep.

**Comment by sakopqiu** [comment]
So to summarize
`es` -> only stage 4
`actual` -> stage 3 + stage 4 + web standards + non-ECMAScript web standards like `URL` or `structuredClone`
`stable` -> stage 4 + web standards + non-ECMAScript web standards like `URL` or `structuredClone`

**Comment by zloirock** [comment]
"Web standards" in you summary is excess since it consists of ECMAScript and "non-ECMAScript web standards".

**Comment by sakopqiu** [comment]
I see, so web standards can be weakly referred to as all the functionalities that most of the modern browsers currently supports, be it a "standard one" or a "non standard but universally implemented one"

**Comment by noinkling** [comment]
@zloirock  Just a side note, but is there a reason why the word "actual" is used specifically? It's not very intuitive for a native English speaker.

I know that "actual" is a false friend in a whole lot of of European languages, where their version instead means "current" in English (see [this page](https://en.wiktionary.org/wiki/Appendix:Glossary_of_false_friends#A) just a few entries down). "Current" would make a lot more sense to me, so I'm wondering if it's simply due to a mixup in meaning.

**Comment by zloirock** [comment]
@noinkling I agree that "actual" is not the best option here. The problem is that "current" is not applicable since "actual" entries include stage 3 proposals - already shipped or ready for shipping in engines - that are not "current" JavaScript. So "actual" here is in the proper meaning. It can confuse, but I was not able to find a better short option. If you have something - feel free to propose it.
