### ISSUE TITLE
Promise extension fails when passing a custom handler to super call

### ISSUE THREAD

**Issue by BarakChamo** [zloirock/core-js#108]
@jimmybot I were trying to implement a promisified `XMLHttpRequest` class by extending the base `Promise` polyfill in babel-core.

An issue exists that we were not able to trace where passing the `super()` call a function other than the one passed to the constructor will throw an error saying: 

```bash 
es6.promise.js:97 Uncaught TypeError: react.rej is not a function
```

when `resolve()` or `reject()` are called inside the problematic promise handler. 

For example:

For the given extension:

```javascript
/* request-class.js */
let handler = (resolve, reject) => resolve('data')

export class BadRequestPromise extends Promise {
  constructor(fn){
    super( handler )
  }
}

export class GoodRequestPromise extends Promise {
  constructor(fn){
    super( handler )
  }
}

/* index.js */
import { BadRequestPromise, GoodRequestPromise } from 'request-promise'


let badRequest = new GoodRequestPromise( (resolve, reject) => resolve() )

badRequest.then( data  => console.log(data) )
badRequest.catch(error => console.error(error) )


let goodRequest = new BadRequestPromise( (resolve, reject) => resolve() )

goodRequest.then( data  => console.log(data) )
goodRequest.catch(error => console.error(error) )
```

The second one will break.

**Comment by zloirock** [comment]
I will explore the problem when I will have a little time.

BTW extending `Promise` with `babel` is a bad idea - [`babel` does not support subclassing native constructors](https://babeljs.io/docs/advanced/caveats/#classes). Currently, most native `Promise` have serious bugs and replaced in `core-js`, but in the future you will have problems.

**Comment by zloirock** [comment]
Looks like it's correct behavior. [`.then`](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.then) should [call your `Promise` subclass constructor](http://www.ecma-international.org/ecma-262/6.0/#sec-newpromisecapability) with [`GetCapabilitiesExecutor` ](http://www.ecma-international.org/ecma-262/6.0/#sec-getcapabilitiesexecutor-functions) which set internal `[[Resolve]]` and `[[Reject]]` methods, but because you change executor in `super` call - these methods will not be added and it should cause error. Need add additional check, error should be thrown before.
