### ISSUE TITLE
corejs@4 progress

### ISSUE THREAD

**Issue by skychx** [zloirock/core-js#1085]
I see that corejs@4 has not had any new commits for 9 months, I would like to ask if there is a specific architecture and schedule for corejs@4?

THX

**Comment by zloirock** [comment]
`v4` branch is not actual.

Now, `master` / `v3` branch requires constant diligent work with significant changes, and rebasing of `v4` on top of it causes tons of conflicts, so I decided temporarily stop work on `v4` branch and move a significant part of non-breaking changes to `v3`.

I'm experimenting with some new fundamental features on local branches and when I will be ready - it will be joined.

Working on `core-js@4` requires many months of complete immersion like it was when I made `core-js@3`, but now I can't afford it - I have a family and I have to feed it. The last time after that, including due to lack of funds, I ended up in prison - I have no desire to repeat such a mistake.

I think I'll publish a post about the current state, the future of the project, and `core-js@4` soon.
