### ISSUE TITLE
Have been reminded for over 3 years now that zloirock is looking for a job

### ISSUE THREAD

**Issue by FirstWhack** [zloirock/core-js#1112]
Did you find one?

**Comment by FirstWhack** [comment]
I've just seen https://github.com/zloirock/core-js/issues/548

> Authors of new negative non-constructive comments related to the postinstall message will be banned. Authors of new similar issues will be banned.

You are free to construe this as negativity, I am genuinely curious if the individual still needs a job!

**Comment by FirstWhack** [comment]
Having reviewed the conduct, I cannot assist in any way to find this individual a job. Best of luck.

**Comment by zloirock** [comment]
A short answer: I'm still looking for.

Initially, this message was added in a critical situation when I could go to prison. If you can search - you can find details.

Now it's another situation. I'm looking for a job where I will be able to work on web standards and devote enough time to FOSS. Otherwise, I will not be able to properly maintain this project that required full-time maintenance.

**Comment by pea-cake** [comment]
加油
