### ISSUE TITLE
Consistency between `lastIndexOf` and `indexOf` 

### ISSUE THREAD

**Issue by verilog15** [zloirock/core-js#1146]
Hello,
I noticed that the `lastIndexOf` and `indexOf` are not consistent with each other when dealing with corner cases. For example:
```
console.log([1,2,3,4,5].lastIndexOf(3,null));
console.log([1,2,3,4,5].indexOf(3,null));
```
The output is:
```
-1
2
```
I would expect both to return `-1` or both to return `2`. Same goes for `undefined` and `NaN`.
I open this issue to consult with you:
- Should they be consistent with each other?
- If yes, I can upload a PR which deals with this case. Which one of those two, should be the output?

**Comment by zloirock** [comment]
Hi @verilog15. `core-js` is just an implementation of the language by the standards, [ECMAScript](https://tc39.es/ecma262/) in this case. By the spec, this is the correct behavior.  Such proposals for the spec discussed [here](https://es.discourse.group/), but I don't think that it is something that can be accepted since at least it's a breaking change for the web.

**Comment by zloirock** [comment]
The answer to why they are not consistent - `null` transformed to `0` in those methods, so `.indexOf` works as without the second argument, but `lastIndexOf` starts from `0` and since it works backward, it check only one element - with index `0`.
