### ISSUE TITLE
`TypedArray.prototype.slice` results in error depending on value

### ISSUE THREAD

**Issue by Sir-Will** [zloirock/core-js#1157]
Hello,
I'm getting the error `TypeError: Unable to get property 'call' of undefined or null reference` with the TypedArray slice polyfill in IE11.

This is what was generated: `_sliceInstanceProperty$1(dst2).call(dst2, 0, compSize);`. 
If I change it to `_sliceInstanceProperty$1("").call(dst2, 0, compSize);` it's working (`dst2` removed from `_sliceInstanceProperty`).

Example code:
```js
const longArray = [];
for (let i = 0; i < 1500; i++) {
    longArray.push(i);
}
const uint8 = new Uint8Array(longArray);
uint8.slice(0, 10);
```

`"@babel/runtime-corejs3": "^7.20.6"`

**Comment by zloirock** [comment]
The pure `core-js` version does not polyfill typed array methods.

Those methods are available in the global version, so you could use it, for example, via `preset-env`.

You see this error instead of the usual `.slice if undefined` because of Babel runtime helpers.

Your hack is incorrect since you try to call `String.prototype.slice` on a typed array.
