### ISSUE TITLE
`core-js-pure/actual/set/difference.js` show unexpected string

### ISSUE THREAD

**Issue by loynoir** [zloirock/core-js#1234]
### Usecase
Use `Set.prototype.difference` ponyfill.

### Reproduce
```js
import setDifference1 from "set.prototype.difference"
import setDifference2 from "core-js-pure/actual/set/difference.js"

const sa = new Set([1, 2, 3])
const sb = new Set([3, 4, 5])

console.log("set.prototype.difference")
console.log(setDifference1(sa, sb))
console.log([...setDifference1(sa, sb)])

console.log("core-js-pure/actual/set/difference.js")
console.log(setDifference2(sa, sb))
console.log([...setDifference2(sa, sb)])
```

### Actual
```
set.prototype.difference
Set(2) { 1, 2 }
[ 1, 2 ]
core-js-pure/actual/set/difference.js
Set {}
[ 1, 2 ]
```

### Expected
```
set.prototype.difference
Set(2) { 1, 2 }
[ 1, 2 ]
core-js-pure/actual/set/difference.js
Set(2) { 1, 2 }
[ 1, 2 ]
```

**Comment by zloirock** [comment]
It shows an unexpected string since it returns a wrapped `Set` instance.

The result of `core-js-pure/actual/set/difference` is not an instance of global `Set`, it's an instance of `core-js-pure/actual/set` - in case of existent global `Set`, it's wrapped `Set` instance with the required interface, complexity, iterability, etc.

There are many different reasons why it's required.
