### ISSUE TITLE
Consider using a ES2015 module bundler

### ISSUE THREAD

**Issue by Swatinem** [zloirock/core-js#125]
Since core-js is extremely modular and uses a lot of very tiny modules, the overhead of the module system itself gets quite big.

How big? According to a simple profile loading the complete core-js is ~70ms, of which `__webpack_require__` amounts to ~20ms (self time). So that’s more than a ¼ performance overhead just for the module system. Plus a lot of overhead in the file size and parsing, so it would even make a much bigger difference.

So how about using a ES2015 module bundler such as [rollup](https://github.com/rollup/rollup). I had a great experience so far using it. It can easily shave off ~60K from a ~300K bundle (unminified) in terms of file size. And completely avoid the overhead mentioned above.

Would you be willing to accept a PR that takes advantage of that? Since rollup has a plugin to consume cjs modules, it might be even possible to do this without any code changes, however I haven’t tried that before.

cc @Rich-Harris

**Comment by zloirock** [comment]
Thanks for the proposal.

In the June I switched `core-js` from `browsirefy` to `webpack` because it saved ~1/4 size. [`__webpack_require__`](https://github.com/zloirock/core-js/blob/v1.2.3/client/core.js#L14-L35) looks enough simple and fast, but called very often, I will try to slightly reduce number of calling this method in the near future. Each `require` adds to minified code only near 5 bytes.

Switching to ES2015 modules makes no sense because it should work with all commonjs module bundlers w/o preprocessing.

`rollup` can work with commonjs, but I don't see any examples. If you will show me it's really more compression-friendly and will be better for performance - possible switch to `rollup`.

**Comment by Swatinem** [comment]
So I made a very ugly hack with zero code changes (just the build script):
https://gist.github.com/Swatinem/4f644b0ba615a0887eac
This also depends on a hacked version of rollup-plugin-commonjs which hardcodes a fix for https://github.com/rollup/rollup-plugin-commonjs/issues/3

The file size difference is 142K vs 124K (core.js unminified)

I did some load time profiling by just having a script tag in an empty file and refreshing that with the chrome profiler open (not very scientific, I know)
webpack ~80-90ms
rollup ~70-80ms

So there is a very small win to be had.

The code that is generated by rollup-plugin-commonjs is also not very optimal, here is a small example:

```
var exports$124 = {};
var module$124 = { 'exports': exports$124 };
// https://github.com/zloirock/core-js/issues/86#issuecomment-115759028
var global$9 = module$124.exports = typeof window != 'undefined' && window.Math == Math
  ? window : typeof self != 'undefined' && self.Math == Math ? self : Function('return this')();
if(typeof __g == 'number')__g = global$9; // eslint-disable-line no-undef
var require$$0$5 = module$124.exports;

var exports$198 = {};
var module$198 = { 'exports': exports$198 };
module$198.exports = require$$0$5.document && document.documentElement;
var require$$3$5 = module$198.exports;

var exports$129 = {};
var module$129 = { 'exports': exports$129 };
module$129.exports = function(it){
  return typeof it === 'object' ? it !== null : typeof it === 'function';
};
var require$$1$1 = module$129.exports;
```

That could be optimized by either rollup-plugin-commonjs itself, or by using real ES2015 modules, but like you said that is very unlikely to happen.

**Comment by Swatinem** [comment]
Please note that I have **not** actually tested that the generated code is indeed correct. Although there were no errors reported in the console.

**Comment by hackwaly** [comment]
> Switching to ES2015 modules makes no sense because core-js should work with all commonjs module bundlers w/o preprocessing.
There is nothing to prevent we doing this.
We can keep source in ES2015 module style. And transpile it to commonjs module style while publish to npm. And bundle it by rollup for browser using.

**Comment by Swatinem** [comment]
That is basically what all the rollup related packages are doing. They are all written in ES6 with modules.

And they are transpiled/bundled for usage in nodejs and the browser separately.

One of the reasoning is that nodes require is dog slow, a lot worse than the in-browser require that webpack generates, since it has to open a lot of small files. You can save a lot of filesystem access by bundling everything into one file. That should massively improve the startup time of node programs pulling in core-js.

**Comment by zloirock** [comment]
> And transpile it to commonjs module style while publish to npm. And bundle it by rollup for browser using.

Unacceptable. It increase size of commonjs modules.

> You can save a lot of filesystem access by bundling everything into one file.

Unacceptable because `core-js` contains too many entry points.

...

I explored this possibility. `webpack` -> `rollup`: minified code size ~ +5%, loading really ~ -10ms. I'm ready to move `core-js` to `rollup` with commonjs modules, but only then [output code will be optimized](https://github.com/rollup/rollup-plugin-commonjs/issues/4). Before that, I close this issue.
