### ISSUE TITLE
[bug] `structuredClone`: cloning views of transferred buffers

### ISSUE THREAD

**Issue by fildahui** [zloirock/core-js#1265]
Hello,

As per the title, when using the `structuredClone` function from core-js with ArrayBuffer and Uint8array (passing in the transfer option too) the results are different when compared to what the global.structuredClone returns.

I noticed it when building a library with webpack 5 and testing the generated bundle (which had the core-js/actual polyfills bundled in it)

You can see the actual issue here https://codesandbox.io/s/relaxed-kepler-mhpyh5, it is a sample app reproducing the code causing the problem, which is what's actually happening in the library I mentioned above (on which, anyway, I do not have control). Just select a file and inspect the console: you will see two objects, the first is the result of the `global.structuredClone` the other is the `core-js` version (in which the `data` property that is supposed to be a Uint8array is different and appears to be empty with length 0).

global structuredClone result:
![image](https://github.com/zloirock/core-js/assets/17295499/37ceb440-a091-4b12-ba02-db7584ed14cb)

core-js structuredClone result:

![image](https://github.com/zloirock/core-js/assets/17295499/1705c4e5-c425-44b8-8de3-df8f4997b0b4)

**Comment by zloirock** [comment]
Thanks. Confirmed and I see the reason.

**Comment by zloirock** [comment]
The problem is that [initially evaluated the transfer logic and only after that cloning](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializewithtransfer). So in the cloning step, we clone an array with a detached buffer. [The `.length` of typed arrays that contain detached buffers is 0](https://tc39.es/ecma262/#sec-get-%typedarray%.prototype.length), we have no direct access to `[[ArrayLength]]`. We should change the order of operations that's problematical with the structured clone algorithm or add some hack. I'll think about it.

**Comment by zloirock** [comment]
I still don't see a perfect solution - all options have some problems. Any ideas?
