### ISSUE TITLE
Is Blob `arrayBuffer()` method being polyfilled?

### ISSUE THREAD

**Issue by yvele** [zloirock/core-js#1273]
I can't find `Blob.arrayBuffer()` is the doc, I'm not sure if it handled by core-js 🤔 

About the Blob: `arrayBuffer()` method:
- https://github.com/w3c/FileAPI/pull/117
- https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer
- https://caniuse.com/mdn-api_blob_arraybuffer
- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1269

**Comment by zloirock** [comment]
Hi. Thanks for the issue.

In my vision, it's out of the current scope of `core-js` - now it covers ECMAScript, ECMAScript proposals, and some **cross-platform Web APIs that are maximally closer to ECMAScript**.

We can't polyfill `Blob` everywhere since it's tightly integrated with and / or represents platform-specific APIs. We can't polyfill `Blob.arrayBuffer` since IIRC we have no ways that will work everywhere (however, I could be mistaken, because I did not delve into this issue).

Theoretically, in the future can be added a `Blob.arrayBuffer` polyfill that will add it in cases where it's possible, however there are many APIs closer to ECMAScript.

**Comment by yvele** [comment]
@zloirock thanks for the detailed answer 👍 

Do you know any equivalent to core-js for the the Web API that includes Blob polyfills?

**Comment by zloirock** [comment]
For such web polyfills, you could take a look at [`core-web`](https://core-web.mrhenry.studio/polyfills/) - however, I see a polyfill for `Blob`, but not for `.arrayBuffer`.
