### ISSUE TITLE
Opt out of core-js-bundle polyfill?

### ISSUE THREAD

**Issue by LeviticusMB** [zloirock/core-js#1285]
I'm using latest `core-js-bundle/minified.js` in a very old runtime (Crosswalk, Chromium 53; previously, we used `core-js/client/shim.js` from 2.6.12).

Unfortunately, `JSON.stringify` is unusable slow. Is there a way to opt out of only that polyfill in this situation?

**Comment by zloirock** [comment]
Sure.

- You could use [`core-js-builder`](https://github.com/zloirock/core-js/tree/master/packages/core-js-builder) and exclude `JSON.stringify`.
- You could use [`core-js/configurator`](https://github.com/zloirock/core-js#configurable-level-of-aggressiveness) (from another copy of `core-js` since it's missed in `core-js-bundle`) and specify it in `useNative`.

**Comment by zloirock** [comment]
Hmm... I forgot that for a legacy reason, before the next major release, `es.symbol` depends on `es.json.stringify`, so the first way also requires the exclusion of the `Symbol` constructor polyfill.
