### ISSUE TITLE
Question: how to automatically manage polyfills imports

### ISSUE THREAD

**Issue by MillerSvt** [zloirock/core-js#1377]
Hi. I admire this library, but it is too heavy. We don't use all the functions in our projects. It would be nice to be able to determine which polyfills are needed and add them to imports in polyfills.ts file.

Now we use angular + webpack, and there is an option to add babel loader + core.js, before angular compiler processes the file (in more detail it described [here](https://github.com/angular/angular-cli/issues/27510)). But we are trying to switch to esbuild and there is no such possibility. The best solution I could come up with was to create a polyfills.ts file before building the application. But how to do it? And how to make sure it doesn't affect performance?

I tried to do this using swc and core.js. I transpiled the files and then searched for core.js imports using a regular expression. However, you need to do this for every file in the project, which is not very convenient. And the idea of a double build itself is not something that would be desirable.

So, my question is: is there a simple way to determine which polyfiles I need? Not just based on the browserslists, but also considering how these functions are used in the project? If there is no such method, maybe you have some ideas where I can look?

**Comment by zloirock** [comment]
`core-js` injection is available in Babel and SWC, it seems you know about it. Most likely, SWC preprocessing with ESBuild will work for you.

The tool that you describe is not available at this moment, but I'm thinking about the creation of this - it was described here - https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md#polyfills-collector

Another option is the usage of [`core-js-builder`](https://github.com/zloirock/core-js/tree/master/packages/core-js-builder) - you can create your `polyfills.ts` with it, for example, like
```js
import builder from 'core-js-builder';

await builder({
  modules: ['core-js/actual'],
  targets: YOUR_BROWSERSLIST_QUERY,
  format: 'esm',
  filename: PATH_TO_YOUR_COREJS_POLYFILLS_TS,
});
```
It will optimize `core-js` for your target engines, but not collect used features - however, it's enough to significantly reduce the size.

**Comment by MillerSvt** [comment]
Thank you! Waiting for polyfills-collector...

**Comment by ddubrava** [comment]
Hi guys, since this is a relatively new issue, I want to ask a silly question here. Why is it not possible (or why isn't there a solution) to analyze our codebase, determine which methods are used (e.g., Set.intersection, replaceAll, or others), and automatically add polyfills for them? Why do we need to include all polyfills based on the browserslist rather than polyfilling only what we actually use in our application?

**Comment by ddubrava** [comment]
Hi guys, since this is a relatively new issue, I want to ask a silly question here. Why is it not possible (or why isn't there a solution) to analyze our codebase, determine which methods are used (e.g., Set.intersection, replaceAll, or others), and automatically add polyfills for them? Why do we need to include all polyfills based on the browserslist rather than polyfilling only what we actually use in our application?

**Comment by MillerSvt** [comment]
@ddubrava 
zloirock says:
> The tool that you describe is not available at this moment, but I'm thinking about the creation of this
