### ISSUE TITLE
The future of core-js

### ISSUE THREAD

**Issue by zloirock** [zloirock/core-js#139]
I love raw javascript, engines compatibility and `core-js` project, but sometimes I want to eat. It's my personal project, in the last year every day I spent several hours for development and maintenance `core-js`. Instead of help with my work, it just creates problems for me. I lost some orders because I spent my time on `core-js` instead of them. At the moment, I try to find a full-time job, but all offers completely unrelated this project. In this case, I will not be able to develop and maintain this project as it's required. I don't see anyone else who can develop and maintain it.

Unlike most other projects, `core-js` development can't be just finished - new specs, new proposals, new engines with new bugs... Finalization of the project means death. And problem for thousands of projects who uses it or repacks (`babel-runtime`, `babel-polyfill`, etc) - in many cases `core-js` hasn't alternatives. I do not want this to happen.

I see only 3 possible way (sure, first two together - the best solution):
- The community can start actively contribute. See more info below.
- Someone can propose me a related job where I will be able to spend enough time for the development and maintenance `core-js`.
- `core-js` will die.

Where can you contribute?
- You can... just report known issues in the tracker. Most issues I see in other places and I have no ideas why just not report them here. I don't want to spend my time finding them.
- You can help with writing tests. Most parts of `core-js` enough well covered by tests, but not completely. And some still not covered, for example, some parts of `Promise` by ES6 spec. Or, for example, you can help adapt `test262` test case.
- You can help check and optimize performance in some places.
- You can help with documentation. I'm not a native English speaker (I think you have understood it after reading of this text :), so it definitely has some bugs, I can miss something else or you can just improve it.
- You can just ask me how you can help more.

**Comment by EisenbergEffect** [comment]
@zloirock First, I just want to say how grateful I and the entire Aurelia team are for your work. This set of polyfills has made it so much easier for us to build the Aurelia platform and enabled us to help thousands of developers all over the world to build next-generation apps.

As an open source developer of over ten years, I personally understand the situation you are in. For the better part of those years, I've lived on far fewer dollars than almost every developer I met because I chose to devote so much of my time and resources to open source work. For at least five months out of this year, while building Aurelia, I didn't pay myself a salary of any kind. I know of other software developers who have made similar or greater sacrifices as well. I'm saying this to let you know that you aren't alone, that your great work is understood and appreciated and in the hopes that you will see the sacrifice you've made as meaningful and helpful to many people. It's a wonderful contribution to our community and in many ways makes the world a better place.

With all that said, I believe strongly that the worker should be paid just wages. You aren't a slave to your open source or to any of us. You're a hard worker and the product of your long hours has tremendous value. You need to survive financially and in such a way that you can be proud of your work and have some mobility. In all honesty, I don't have a solution for you on the financial side yet. I'm talking with the Aurelia team about your situation and I've got some partners that could be interested. I'm going to reach out and explore some possibilities for you. Please email me privately. You can get my email from my github account. I look forward to hearing from you and let's see how we can put something together that enables both you and your project to thrive.

**Comment by zloirock** [comment]
For 2 months the situation has not changed. Ok.

**Comment by jdalton** [comment]
If you're looking to cut back I think time would be well spent modularizing [es5-shim and es6-shim](https://github.com/es-shims/) as they're the de-facto shims.

**Comment by zloirock** [comment]
Dear @jdalton, I started writing `core-js` mainly because of problems in `es6-shim`. Slow polyfills, `O(n)` collections, missing most shams, many shims, modularity, impossible to use any `Symbol` polyfill (just because of that you can't use most `babel` features), to use without global namespace pollution (and with modularity and current `es-shims` conceptions it is problematic), etc. And there are no any progress. "De-facto shims" - your delusion, currently de-facto shims - different utilizing `core-js` packages. Compare downloads [`core-js`](http://npm-stat.com/charts.html?package=core-js&author=&from=2014-11-18&to=2114-11-18) and [`es6-shim`](http://npm-stat.com/charts.html?package=es6-shim&author=&from=2014-11-18&to=2114-11-18). So you really think it can be simply fixed? :)

**Comment by jdalton** [comment]
ES-shims are pretty well established outside of npm. Responsible, quality shims are great. The point isn't to sham-all-things. If you're unable to continue your work it makes sense to work with the es-shim folks.

**Comment by zloirock** [comment]
Oops, looks like you update you comment.
> Have you thought about giving es-shim authors commit rights since their interests align with yours?

It might be interesting because we do the same thing.
> Responsible, quality shims are great.

I reported too many bugs about `es-shims` :)
> The point isn't to sham-all-things.

The problem here - actual polyfills from `es6-shim` can't replace most `core-js` use cases.
> If you're unable to continue your work

Here I am just looking for the opportunity to continue this work.

**Comment by jdalton** [comment]
Great! I think working with them would help ease the load.

**Comment by JSteunou** [comment]
my 2 cents:

I though about the same. es6-shim team talked about splitting stuff in modules 9 month ago https://github.com/paulmillr/es6-shim/issues/297 (with @jdalton showing the light ;) ) but v1 will be without it https://github.com/paulmillr/es6-shim/issues/404

I think all of you need times and forces for maintaining those giant projects, and joining in a common project could solve everyone issues.

If you could work together I see a lot of advantages: more forces, more minds, modular project, one community brought together which could lead to ease of PR and other helps, less struggle for us to choose which shim to use...

I even dream of some polyfill no being in that kind of project, but a link / sub repo of other popular polyfill (think of Promise for example). I know there is some strong bounds between those shims, but maybe some could be maintain by another dedicated team in order to reduce the effort.

**Comment by ysmood** [comment]
@zloirock I think I would like to take care of the maintenance of promise module. Hope I can help you to shoulder some burden.

#170 is my first step towards it, and more test cases will be added.

**Comment by steida** [comment]
You should add Bitcoin donate like http://sokra.github.io/

**Comment by tregusti** [comment]
I fully agree, use flattr and gratipay and paypal for instance! Your project have helped my alot so I would pay some for it. And though I am quite new at using this lib, I will create PRs for the problems I find.

**Comment by astec** [comment]
Angular2 just switched to your lib - https://github.com/angular/angular/commit/66df335998d097fa8fe46dec41f1183737332021

Send CV to Google!

**Comment by OleksiiZubko** [comment]
@zloirock core-js should not die and I believe the situation will be better, at least after Angular 2 devs. started use it.  Thanks for the great lib.

**Comment by balupton** [comment]
Has anything changed? Been nearly a year now without updates.

I've found open-source development to be exactly the same - packages get millions of downloads a month - but no funding at all. In 2014 I quit my open-source stuff for nearly 2 years because of it. I have some ideas for funding these days, but nothing concrete.

**Comment by EisenbergEffect** [comment]
I've been doing open source for over ten years and rarely had any sort of funding even though tens of thousands of companies were basing their entire business on products built with my tech. It's a sad situation when even some billion dollar organizations aren't willing to get behind stuff that they depend on to survive.

**Comment by Bessonov** [comment]
I wrote to @zloirock by email, but I did not receive an answer. Maybe the email ended up in spam. I am looking for very good frontend/backend/fullstack developers for a German company.

**Comment by charneykaye** [comment]
After seeing the funding notice when I installed NPM, I showed up here wondering if the author was being a little too shameless in self promotion.

I swiftly realized that **core-js** is integral to modern front-end JavaScript UI at a global scale.

I thoroughly agree with @EisenbergEffect that our society must cut new pathways for some of the money from these massive corporations to make it to the individual contributors who work ceaselessly to support open-source software development.

For now, I'm going to take a step towards that future by becoming a conduit myself. I anted up US $1/month for @zloirock to work on this project. That's a tiny amount, but think about this-- **If 1% of the individuals on the "used by" list for this repository contributed $1/month, it would add up to $23,768.97/month.**

**Comment by seyfer** [comment]
Because now I have this in the output

```
17:52:05 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
17:52:05 
17:52:05 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
17:52:05 > https://opencollective.com/core-js 
17:52:05 > https://www.patreon.com/zloirock 
17:52:05 
17:52:05 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```

Our Jenkins CI fails.

Seriously?

**Comment by jdalton** [comment]
Hi @seyfer!

Plenty of projects output a little message on use (Babel, Webpack, even npm when it's time to update). Your Jenkins fail is a bummer, but this is a minor hiccup that I expect will continue as other projects do the same. Taking your frustration out on an author who does this largely for free, in their own time, is prolly not the best of approaches. This is a good opportunity to help support the project/author instead 🤝 :heart:

**Comment by seyfer** [comment]
@jdalton well, we are using such way for dependencies installation
`OPENCOLLECTIVE_HIDE=true npm ci --unsafe-perm --no-save`
which switches off these `support us` messages for all other deps, except this one.
Was it added somehow in the wrong way?

I appreciate the author work. But I think that if thousands of projects rely on your work it also involves some degree of responsibility. And despite the personal situation, it is not a reason to create troubles for users.

Btw. my problem with CI was resolved. :sweat_smile:

**Comment by seyfer** [comment]
@zloirock > I see only 3 possible way (sure, first two together - the best solution):
I see 4th
You can try to find maintainers, give them access to the code and delegate some responsibilities. I believe many would like to join as it is a good addition to their CV. :smile:

**Comment by zloirock** [comment]
@seyfer this thread is not a correct place for your issue about the `postinstall` message. At this moment, you can use `ADBLOCK` variable, in the next release - `DISABLE_OPENCOLLECTIVE`, which used in the official Open Collective package.

Sure, your option about maintainers is perfect, but I don't see any candidates -) Anyway, need to update the state of this issue since it was opened a long time ago.
