### ISSUE TITLE
instanceof Map broken when mixing with non-polyfilled code

### ISSUE THREAD

**Issue by letmaik** [zloirock/core-js#147]
I use Babel for transpiling and it automatically uses core-js's Map polyfill. I also have an ES5 non-transpiled library I use in the same project which doesn't use the Map polyfill (as I set that as a minimum browser requirement). When I hand over a Map instance from the ES6 code part to the ES5 code and then do `map instanceof Map` it evaluates to false.

I know that the underlying problem is that I should consistently use polyfills or not, and apply them at the very beginning before any other code runs, then instanceof would also work as expected.

But what I find a bit strange is that the polyfill gets active at all even though the browser supports it already (latest Firefox/Chrome). I thought that core-js only jumps in when support is missing?

**Comment by zloirock** [comment]
For some reason, it's expected behavior. `core-js` should add properties to prototypes of collections / wrap constructor (in this case should be `new Map().constructor === Map`), etc. So in `library` version collections are wrapped and internally uses native collections. This allows modify the prototype and causes a slight deceleration. I already have some issues about it and I think about removing wrapping (in this case in most engines will be `new Map().constructor !== Map`) or adding to prototype chain prototypes of native constructors (but it can cause some conflicts).

**Comment by zloirock** [comment]
Changing status to `discussion` - maybe someone can offer a better solution.

**Comment by zloirock** [comment]
Leave it as is.
