### ISSUE TITLE
Symbols shouldn't be instances of Symbol

### ISSUE THREAD

**Issue by sebmck** [zloirock/core-js#16]
```javascript
> Symbol() instanceof Symbol
true
```

should be `false`.

**Comment by zloirock** [comment]
@sebmck How do you propose to implement similar:
```javascript
Symbol() instanceof Symbol // => false
Object(Symbol()) instanceof Symbol // => true
```
Avaliable wrapper for `Object`, but I don't think this a good idea.

**Comment by sebmck** [comment]
@zloirock Not sure, I'm currently testing 6to5 and core-js against the traceur test suite. Here's where they do it: https://github.com/google/traceur-compiler/blob/196ad464969df96fafbbf248047ead5a6deae694/src/runtime/runtime.js#L117

**Comment by zloirock** [comment]
@sebmck [try in IE](http://google.github.io/traceur-compiler/demo/repl.html#console.log(Object(Symbol())%20instanceof%20Symbol)%3B) . I think it is better to leave as is.

**Comment by zloirock** [comment]
@sebmck I do not know how to fix it without breaking something else. If there will be ideas, i will fix it.

**Comment by WebReflection** [comment]
FWIS the way I've resolved this is creating a `new String` once, defining also it's constructor once.

Example:
```js
return (source[uid] = defineProperty(
  Object(uid),
  'constructor',
  sourceConstructor
));
```

`source` is the internal private map that holds the Symbol as `typeof "object"` but `instanceof String`, instead of `Symbol`, with `sourceConstructor` that is the equivalent of the following descriptor:
`{value: Symbol}`

This makes Symbol hopefully well optimized as properties accessors since these are `String` at all effects ... however, I'm not sure it's any better than a private constructor with a `valueOf` / `toString` overwrite so this might be a valuable alternative:

```js
function SymbolWrap(value) {
  Object.defineProperty(this, 'value', {value: value});
}
Object.defineProperties(
  SymbolWrap.prototype,
  {
    constructor: {value: Symbol},
    valueOf: {value: function valueOf() {
      return this.value;
    }}
  }
);
Object.defineProperty(
  SymbolWrap.prototype,
  'toString',
  {value: SymbolWrap.prototype.valueOf}
);
```
Or even this one
```js
function createSymbol(value) {
  function valueOf() { return value; }
  return Object.defineProperties({}, {
    toString: {value: valueOf},
    valueOf: {value: valueOf}
  });
}
```

**Comment by zloirock** [comment]
`new String` really interesting possible optimization.
