### ISSUE TITLE
Custom build only what necessary 

### ISSUE THREAD

**Issue by jimmywarting** [zloirock/core-js#167]
Is there anyway you can run a test script in one browser and depending on what it (doesn't) support you would get a terminal command to build a custom package with only what is necessary just for that browser?

**Comment by zloirock** [comment]
Available [native features test](http://raw.githack.com/zloirock/core-js/master/tests/native.html) (in theory currently can crash some browsers). I don't think getting a terminal command in a similar test makes sense because the most frequent aim is a several browsers / engines - anyway a list will be formed manually.

**Comment by zloirock** [comment]
I don't see here any discussion / proposals, so the issue is closed. Related and may be available in the future: https://github.com/Financial-Times/polyfill-service/issues/421 (looks like work resumed).

**Comment by jimmywarting** [comment]
Thanks, might be just what I'm looking for
