### ISSUE TITLE
Why polyfill is used when native is supported? (Promise)

### ISSUE THREAD

**Issue by wintercounter** [zloirock/core-js#191]
I'm using `babel-polyfill`. I always have such stack trace:

```
(anonymous function)	        @	es6.promise.js:119
perform	                                @	es6.promise.js:61
(anonymous function)	        @	es6.promise.js:113
module.exports	                @	_invoke.js:5
queue.(anonymous function)	@	_task.js:31
run	                                        @	_task.js:19
listener	                                @	_task.js:23
```

The question is simple. Why? Chrome has support for native Promises (this is a Chrome stack trace).

**Comment by zloirock** [comment]
Almost all current `Promise` implementations have many bugs and most of them can't be fixed without completely replacement `Promise` constructor, you can find many V8 bugs in this tracker. Current feature detection for `Promise` includes support `@@species` pattern (the ultimate feature detection for almost all `Promise` bugs, support `@@species` should be added in V8 ~ Chrome 51) and unhandled rejection tracking (added in V8 ~ Chrome 49), so native `Promise` will be used instead of polyfill only in V8 ~ Chrome 51.

**Comment by wintercounter** [comment]
Thanks for the answer.
