### ISSUE TITLE
consider removing Observable from es7

### ISSUE THREAD

**Issue by gdi2290** [zloirock/core-js#200]
Hey Denis, it's confusing for new devs, when learning `Observable`, to understand the difference between the polyfill'd and RxJS version. Once Angular 2 switches to `core-js` (as the goto polyfill rather than `es6-shim`) a lot of devs will start questioning why the global one doesn't have any operators vs importing RxJS. RxJS 5 also has some optimizations in their version of `Observable` which will allow things like `lift` for Observable operators. Once `Observable` becomes Stage 2 then it may make sense for RxJS to consider checking for a global type before creating it's own.

cc @blesh, Chief of `Observable`

**Comment by zloirock** [comment]
Hi. I don't think it can be removed from this namespace because this namespace for features like it. This namespace named `es7` only for compatibility with old old versions and will be renamed to `esnext` in the next big release. I totally agree that proposal-only implementation is not so useful like `RxJS` - [many required methods just not added to the spec](https://github.com/zenparsing/es-observable/issues/76#issuecomment-176704826). If someone wanna use `RxJS` - he should use `RxJS`, not global `Observable` because then it will be added to engines - will be added only parts, available in `core-js`.

**Comment by gdi2290** [comment]
thanks! that does clear up a few concerns

**Comment by blesh** [comment]
I suppose RxJS can do what bluebird does and just trample the one in global scope.
