### ISSUE TITLE
Support frozen objects as Map and Set keys

### ISSUE THREAD

**Issue by AgentME** [zloirock/core-js#23]
```javascript
var core = require("core-js");
var map = new Map();
var key = Object.freeze({});
map.set(key, 123);
```

This throws an exception, even if your environment has native Maps (`node --harmony`) which can handle immutable keys fine.

```
/Users/chris/Coding/test/node_modules/core-js/library.js:374
    return defineProperty(object, key, descriptor(bitmap, value));
           ^
TypeError: Cannot define property:Symbol(uid)_g.qtbu3c1d5v29be29, object is not extensible.
    at defineProperty (native)
    at /Users/chris/Coding/test/node_modules/core-js/library.js:374:12
    at fastKey (/Users/chris/Coding/test/node_modules/core-js/library.js:1393:17)
    at def (/Users/chris/Coding/test/node_modules/core-js/library.js:1401:17)
    at getCollection.set (/Users/chris/Coding/test/node_modules/core-js/library.js:1468:14)
    at Object.<anonymous> (/Users/chris/Coding/test/index.js:4:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by zloirock** [comment]
Core-js >= 0.3.0 replace native `Map` and `Set` if they not support iterators, otherwise only fixes broken methods. Why? We can't implement fast & correct iterators using only `.forEach`.

About frozen objects as keys in polyfill I wrote in readme yesterday. Why core-js collections not support frozen objects as keys? For better performance (O(1) vs O(n)), they store keys on hash table. Native hash table in ES5 is only `Object`. `Object` support only strings as keys. We add hidden id property for object keys. Maybe I will add slow fallback for this case in the future.

IO.js and latest 0.11 Node.js, FF, V8 browsers has native collections with iterators.

**Comment by AgentME** [comment]
Could it be made to fall back to using an array to store frozen objects? I assume it does that for primitives.

**Comment by zloirock** [comment]
It's very slow and is not suitable for other reasons. Possible to add entries to the chain without adding to the hash table. I'll see when I have time.
