### ISSUE TITLE
Confused how to import only certain features, for polyfill only

### ISSUE THREAD

**Issue by flyon** [zloirock/core-js#242]
Sorry for asking something very obvious but I'm just getting a bit confused by all the options

If I want to import only Set and Map for commonJS in my bundle, only to shim/polyfill older browsers, and use the global Set and Map in my code. How do I do that?

```
var Map = require("core-js/es6/map");
var x = new Map();
```

If I do it like this, will newer browsers still use their own implementation of Map? And if I build with webpack will my bundle _only_ include the shim for Map?

**Comment by zloirock** [comment]
If you wanna use the only certain polyfill, for example, `Map` - you can add at the top of your entry point just `require("core-js/es6/map");` and use global `Map`. If the environment has enough good native `Map` - it will be native `Map`. If native `Map` has some minor problems - it will be fixed, but anyway, you will use native implementation. Otherwise, it will be the polyfill. With `require("core-js/es6/map");` you will have *only* `Map` polyfill with dependencies in the bundle.
