### ISSUE TITLE
Error on 'new ArrayBuffer();'

### ISSUE THREAD

**Issue by shaibam** [zloirock/core-js#273]
We've noticed that when babel-polyfill is loaded it overides the ArrayBuffer constructor.
an error occurs when creating a new ArrayBuffer without arguments

new ArrayBuffer();
polyfill.min.js:2 Uncaught RangeError: Wrong length!
at $ (polyfill.min.js:2)
at new ArrayBuffer (polyfill.min.js:2)
at :1:1
Input Code

**Comment by zloirock** [comment]
[It's a correct behaviour by the spec.](http://www.ecma-international.org/ecma-262/7.0/#sec-arraybuffer-length)

**Comment by eirslett** [comment]
Can this issue be reopened? The spec has changed a bit, you're allowed to call `new ArrayBuffer()` without the `length` argument. (Though the changes I link to were done already in June 2016, which is before this issue was closed, so maybe I've missed something)

[This is the change](https://github.com/tc39/ecma262/pull/410) that was made to the spec. [This is the tc39/test292 commit](https://github.com/tc39/test262/commit/cfc77c83e3ccbf0070968f01cd3ff7a904975b40) that updates the unit test suite to reflect the change. (Maybe they have been reverted back and forth since then?)

Anyways, in the latest versions of Chrome and Firefox, you can do `new ArrayBuffer()`, and length will default to 0. There are already open source libraries out there that exploit that behavior, for example [mp4box](https://gpac.wp.imt.fr/mp4box/), which then unfortunately doesn't work with core-js...

**Comment by loganfsmyth** [comment]
This is now open in https://github.com/zloirock/core-js/issues/293#issuecomment-291676118 I believe.

**Comment by KagamiChan** [comment]
Hitting this issue using `babel-polyfill` together with `whatwg-fetch` when calling `Response.arrayBuffer()`, please consider fixing it

code from core-js
```
var validateArrayBufferArguments = function(that, length){
  anInstance(that, $ArrayBuffer, ARRAY_BUFFER);
  var numberLength = +length
    , byteLength   = toLength(numberLength);
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
  return byteLength;
};
```
```
    $ArrayBuffer = function ArrayBuffer(length){
      return new BaseBuffer(validateArrayBufferArguments(this, length));
    };
```

polyfilled code:
```
        return _regenerator2.default.wrap(function _callee$(_context) {
          while (1) {
            switch (_context.prev = _context.next) {
              case 0:
                source = new window.ArrayBuffer();
                _context.prev = 1;
                _context.next = 4;
                return window.fetch(url);
```

**Comment by KagamiChan** [comment]
turns out that I wrote myself `window.ArrayBuffer()`, blush 🤦‍♂️
