### ISSUE TITLE
Object.observe

### ISSUE THREAD

**Issue by daliwali** [zloirock/core-js#33]
`Object.observe` has already landed in Chrome and Opera, and is part of the ES7 proposal. There is [a polyfill](https://github.com/MaxArt2501/object-observe) that already supports it. Are there any plans for this feature to land in core-js?

**Comment by zloirock** [comment]
`Proxy` and `Object.observe` can't be fully polyfilled. That polyfill has [many limitations](https://github.com/MaxArt2501/object-observe#limitations-and-caveats). Dirty checking observable object on `requestAnimationFrame` loop limits its use in practice because of the huge overhead. I don't think it should be added in core-js.
