### ISSUE TITLE
Missing ES6 methods which were optional in ES5

### ISSUE THREAD

**Issue by chocolateboy** [zloirock/core-js#336]
> :bulb: Some implementations of ECMAScript have included additional properties for some of the standard native objects. This non-normative annex suggests uniform semantics for such properties without making the properties or their semantics part of this standard. -- [ECMA-262 Edition 5.1 / Annex B / B.2 Additional Properties](https://www.ecma-international.org/ecma-262/5.1/#sec-B.2)

`String.prototype.substr` is [optional](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr#Specifications) in ES3 and ES5 but required in ES6. While [all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr#Browser_compatibility) appear to have implemented it before the semantics became normative — [incorrectly](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr#Polyfill) in at least some version(s) of IE — its optional status is not just hypothetical. It's behind a [build-time flag](https://github.com/svaarala/duktape/blob/827183afab50339d4c01da0fd9191d5eb3e9c833/config/config-options/DUK_USE_SECTION_B.yaml#L10-L11) in [Duktape](https://github.com/svaarala/duktape) and [missing](https://github.com/ccxvii/mujs/blob/8c27b1260d418feff94b033db3f721c8d7ee4e01/jsstring.c#L667-L690) from e.g. [MuJS](https://github.com/ccxvii/mujs):

> The scripting backend which mpv currently uses is MuJS - a compatible minimal ES5 interpreter. As such, `String.substring` is implemented for instance, while the common but non-standard `String.substr` is not. -- [mpv manual](https://mpv.io/manual/master/#language-features-ecmascript-5)

Other missing methods that are optional in ES5 and required in ES6 include:

* global.escape
* global.unescape
* Date.prototype.getYear
* Date.prototype.setYear
* Date.prototype.toGMTString

**Comment by loganfsmyth** [comment]
> optional in ES3 and ES5 but required in ES6

I feel like this varies depending on how you look at it. These are all defined in Annex B, https://www.ecma-international.org/ecma-262/8.0/#sec-additional-ecmascript-features-for-web-browsers, which says

> The ECMAScript language syntax and semantics defined in this annex are required when the ECMAScript host is a web browser. The content of this annex is normative but optional if the ECMAScript host is not a web browser.

You specifically mention `DukTape` and `MuJS`, but these seem perfectly spec compliant to me because they are indeed not "web browser" environments.

So the question is, is it `core-js`'s job to polyfill things that are not required in all ES6 environments. `core-js` is also used in many non-browser contexts, and it has no 100%-guaranteed way to know whether something is a browser. I could see an argument that these could be implemented as an optional opt-in alongside the normal `core-js` entry points, but on the other hand the fact that these are optional in some environments means that they should essentially never be used in any code written today.
