### ISSUE TITLE
SCRIPT5045: Assignment to read-only properties is not allowed in strict mode IE11

### ISSUE THREAD

**Issue by varadharajan007** [zloirock/core-js#341]
when try to open my angular2 project in IE11, i am getting this error

"SCRIPT5045: Assignment to read-only properties is not allowed in strict mode
vendor.bundle.js (8031,5)".

In vendor.bundle.js file ,
Debugger is point on this function
--> ObservableArray.prototype.find = function (predicate, thisArg, fromIndex) {
        if (fromIndex === void 0) { fromIndex = 0; }
        var idx = this.findIndex.apply(this, arguments);
        return idx === -1 ? undefined : this.get(idx);
     };

please let me know about solutions.

**Comment by zloirock** [comment]
I don't see anything related `core-js` here. `ObservableArray` is not a part of `core-js`.

**Comment by mweststrate** [comment]
See also: https://github.com/mobxjs/mobx/issues/1028#issuecomment-376996056. The MDN official polyfill incorrectly creates a non-configurable, non-writable property. (Just submitted an issue to MDN to fix that). 

If core-js also introduces `Array.prototype.find` with a property descriptor that is not: `{ configurable: true, enumerable: false, writable: false}`, than this could be an issue. 

Since I am completely unfamiliar with core-js, I don't know how to check that quickly (couldn't find it in the source code)

**Comment by zloirock** [comment]
@mweststrate by the spec, `Array.prototype.find` descriptor should be `{writable: true, enumerable: false, configurable: true}` and `core-js` use it. Because of usage`defineProperty` in  `core-js` for polyfilling `Array.prototype.find`, this incorrect descriptor from MDN polyfill should not be a problem. How it's related this issue?

**Comment by mweststrate** [comment]
I don't know if it is related, hence the question :) I wanted to check that, but didn't know how (I don't have a project using core-js in its build lingering around anywhere, and searching the sources didn't give a clue), so figured I could ask instead :-).

I got this issue reported a few times, but most people themselves hardly know where their polyfills are coming from, so wanted to double check that core-js isn't causing it.

Thanks for the info!
