### ISSUE TITLE
Invalid flags supplied to RegExp constructor 'y' 

### ISSUE THREAD

**Issue by fernandogmar** [zloirock/core-js#372]
Hi Denis,

I expected that the RegExp polyfill would work with the sticky flag 'y'
`var identifierRe = new RegExp('[a-zA-Z_][a-zA-Z0-9_-]*', 'y');`

but in safari v9.1 it fails with error:
`Invalid flags supplied to RegExp constructor`

Am I doing something wrong? or doesn't this polyfill support the sticky flag at all?

Thanks in advance!

**Comment by zloirock** [comment]
Hi. The sticky flag support is not polyfilled in `core-js`. After [this discussion](https://github.com/babel/babel/issues/904) I spent some time playing with the sticky flag but I didn't add it IIRC because of problems with some early implementations. At this moment, adding support for the sticky flag is not in my plans. Feel free to add a PR.
