### ISSUE TITLE
Symbol polyfill not working with old mobile Chrome

### ISSUE THREAD

**Issue by hyperknot** [zloirock/core-js#406]
I'm using `for of` loops with babel, the generated code is something like this:

```
var n = !0,
  r = !1,
  i = void 0
try {
  for (var u, l = t[Symbol.iterator](); !(n = (u = l.next()).done); n = !0) {
    var c = u.value
    !(function(e) {
      // code
    })(c)
  }
} catch (e) {
  ;(r = !0), (i = e)
} finally {
  try {
    !n && l.return && l.return()
  } finally {
    if (r) throw i
  }
}
```

My polyfill is:
```
require('core-js/es6/symbol')
```

This combination works well, except in some old Chrome Mobile browsers (which I cannot test, I only receive Sentry errors).

The given error is `undefined is not a function` for the Symbol.iterator line (can be both the iterator or maybe the `.next()` I guess.

Browsers which has triggered this bug so far: Chrome Mobile 38 and 40.

**Comment by zloirock** [comment]
Seems the problem not in the `Symbol` polyfill. `core-js` tested in those envieronments. You should also add a polyfill of required iterator. If `t` is an array, it should be `Array` iterator polyfill. For example, `core-js/fn/array/iterator`.

**Comment by hyperknot** [comment]
I see. It's a `HTMLCollection` from `getElementsByClassName`. typeof says it's an object.

**Comment by zloirock** [comment]
Therefore, `core-js/fn/dom-collections/iterator`.

**Comment by hyperknot** [comment]
Thanks!

**Comment by hyperknot** [comment]
I've added the iterator but old Chrome Mobile still throws the same exception. My polyfills now look like this:

```
require('core-js/es6/map')
require('core-js/es6/set')
require('core-js/es6/symbol')
require('core-js/fn/array/includes')
require('core-js/fn/dom-collections/iterator')
require('core-js/fn/number/is-integer')
require('core-js/fn/object/values')
require('core-js/fn/string/from-code-point')
require('core-js/fn/string/from-code-point')
```

**Comment by zloirock** [comment]
I have no ideas. Does it work with just `require('core-js/shim')`? Could you add a reproducible example?

**Comment by hyperknot** [comment]
To be honest it's not really a big deal, those browsers are already super rare and hopefully will disappear. I cannot reproduce it as I don't even have a device, just a Sentry exception trace from time to time.

**Comment by danieltroger** [comment]
Hi guys, I have had this issue in my sentry for a few weeks now and it has been bothering me like crazy.

I have finally, after trying every old chrome on the internet, been able to reproduce.

It seems to be a chrome bug in ~chrome 39 (and also samsung internet 3.3) as @hyperknot said.

And it is, I think, also described here: https://github.com/zloirock/core-js/issues/37#issuecomment-75811905

I am a bit bummed I only found your thread now though, after trying for hours to fix this and find the error in parcel, babel and now finally core-js.

I wanted to open an issue and when checking to not open a duplicate I found this. Could you maybe reopen it? It is clearly an issue and is affecting people stuck on android 5 due to their phones not being updated.

HOW TO REPRODUCE: download and install this: https://developer.android.com/studio

open a random APK or something else to show the button labeled "AVD manager".

set up a a new virtual device in the android virtual device manager, select pixel xl. For the OS select android 5.1 (you have to click "download" first or it will be greyed out.

Open up "browser" in the virtual android device.

Open up chrome on your computer and go to `chrome://inspect`. The virtual device should show up there and you should be able to open a remote console.

My observations: the code provided by this [babel repl](https://babel.dev/repl#?browsers=chrome%2038&build=&builtIns=entry&spec=true&loose=false&code_lz=MYewdgzgLgBA1gSwCYRgXhmApgdxgEQHkBZABQEMAnCLSgCgEoA6ABypoDFKQBbAZSiUEYAOZ0ABgB4WAPgAWWAJ6SA9LOnyQq2eIA0MAERQsADygq5UHgBsDzAEYgkipsDkJrSSljABuAFCBAGYg9KCQsFjWWDw-sCBB8MgQDADe_jAw4RAg0UzWIGJRMXEMAQC-_kA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.13.8&externalPlugins=) throws `TypeError: Invalid attempt to iterate non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`.

It only happens when using for of on something that's not an array, spreading it works.

![Screen Shot 2021-02-28 at 02 32 55](https://user-images.githubusercontent.com/4047180/109405105-4c187700-796d-11eb-947c-1d13b497cc55.jpg)

Please help you're my last hope before removing all `for of` loops in my code or shamefully admiting my defeat.

**Comment by danieltroger** [comment]
@zloirock also this is clearly a bug. Just maybe a chrome bug. But like, core-js polyfills Symbol's and it's job is to make shit work on old browsers so this should work.

Also excuse my paranoia but I've just read like 5 wontfix issues on this blaming people to implement symbol.iterator support themselves and debugging this already cost me way too much time.

**Comment by zloirock** [comment]
@danieltroger now we can afford to completely replace `Symbol` in Chrome 38-40, so I'll add a workaround for this Chrome bug.

**Comment by danieltroger** [comment]
@zloirock I don't understand why it's expensive and you couldn't do it before? And I'm surprised the issue actually is that the symbol.iterator only exists in the prototype and not in instances, as I believe it didn't exist in instances either when I tested it in the newest version of firefox. But maybe I did something wrong.

Also, did you know what the issue was all along or did my research about how to reproduce help?

However it is, if it's now fixed: THANK YOU, that's amazing!

**Comment by zloirock** [comment]
@danieltroger #37 was created when Chrome 39 was the most recent browser and `core-js` didn't add polyfills for `HTMLCollection` methods. Fixing this issue is possible only with the complete replacement of `Symbol` - it was too expansive only for that. After that was added a polyfill for iterable array-like DOM collections, after some time because of another issue `Symbol` constructor was completely replaced in Chrome 38. But I forgot about this issue in Chrome 39-40.

**Comment by danieltroger** [comment]
Ahh, I see. Thanks for explaining and great that it's fixed now!

**Comment by danieltroger** [comment]
![Screen Shot 2021-03-01 at 16 29 07](https://user-images.githubusercontent.com/4047180/109519160-4759dd00-7aab-11eb-9249-6e9e80d42175.jpg)

Can confirm it's working :)
