### ISSUE TITLE
Question around bind operator and virtual methods

### ISSUE THREAD

**Issue by diervo** [zloirock/core-js#418]
This is more a clarification than an issue.

Let me start saying that we at Salesforce are using core-js for our IE11 support, and we are fundamentally grateful for all the work being done here.

Because this is probably the best up-to-date project for polyfill in production (including the integration for babel), I found misguided the new APIs and the use of syntax that is not the path of standardization.

I love the idea of having polyfills that do not pollute intrinsics so you can isolate multi-author code in the same REALM, however IMHO the fact that it uses syntax not even in the path for standardization is wrong, and should not be advertised as part of the main api.

I would love to help make the previous statement happen, but not at the expense of developers writing code that might never be valid javascript.

I would love to understand the rationale for this changes if Im missing something.

**Comment by zloirock** [comment]
Sorry, I don't know how I missed this issue. At first, thanks for the good words.

I don't understand what do you mean by "I found misguided the new APIs and the use of syntax that is not the path of standardization". It's [an early-stage proposal](https://github.com/tc39/proposal-bind-operator), it's in [the list of actual ES proposals](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md#stage-0-proposals) (so it's in a path of standardization, however, a long time without advancement), it's available as [an official `babel` plugin](https://babeljs.io/docs/en/babel-plugin-proposal-function-bind) and the example uses the correct syntax from this proposal.

It's only one of the possible use cases of `/virtual/` methods - for example, they used also in `@babel/runtime`. There are alternative APIs, so I can't understand this issue.

However, I agree that since the bind operator is an early-stage proposal makes sense to add a notification about it.
