### ISSUE TITLE
Differences between core-js/library/modules & core-js/modules

### ISSUE THREAD

**Issue by jchnxu** [zloirock/core-js#423]
Here's the problem: 

The contents of `core-js/modules/es6.object.assign` & `core-js/library/modules/es6.object.assign.js` are identical. What's the difference, I mean the design concerns, between the files under `core-js/library/modules` and the ones under `core-js/modules`? 

## Background: 

I am using `babel-polyfill`, which requires `core-js/modules/es6.object.assign`.

But I'm also using some library that uses babel-runtime `require('babel-runtime/helpers/extends.js')`. This is normal because it's the job of babel-runtime to shim helpers. (FYI: https://babeljs.io/docs/en/babel-plugin-transform-runtime, I use the config {polyfill: false, regenerator: false} of transform-runtime). 

This `extends` function eventually leads to `core-js/library/modules/es6.object.assign.js`. Hence I have two implementation of Object.assign.

**Comment by zloirock** [comment]
`core-js` is a global polyfill, `core-js/library` - a version without global namespace pollution. A serious part of files for them looks the same, but because of different logic in other files, they have a different internal state. It's hard to make them common and it could seriously increase bundles size in some cases. If you use a global polyfill, you can just add it as a webpack alias for a version without global namespace pollution, something like `core-js/library` -> `core-js`.
