### ISSUE TITLE
String.prototype.replace

### ISSUE THREAD

**Issue by LordStriller** [zloirock/core-js#470]
Since version 2.6.0 the verification:

` 'prototype' in String.prototype.replace`

fails because the function is being redefined in the es6.regexp.replace.js file which in turn breaks in the code I'm currently working on

**Comment by zloirock** [comment]
Since version 2.6.0, `String.prototype.replace` should be polyfilled in a serious part of modern engines.

To prevent problems like your, `core-js` hide that something is polyfilled, for example, by wrapping `Function.prototype.toString`. But, my congratulation, this detection that a method is native works fine.

It should be polyfilled and we have no way to hide that the method is polyfilled from this detection for all possible engines. So this issue can't be fixed in `core-js` scope. I can only recommend avoiding feature detection like this.
