### ISSUE TITLE
Missing data in core-js-compat?

### ISSUE THREAD

**Issue by renchap** [zloirock/core-js#507]
I upgraded my project to latest `babel` & `core-js@3` and I am seeing unexpected polyfills with running a build targetting browsers that support ES modules (`targets: { esmodules: true }`) in `babel-preset-env` settings (which is mapped to [those browsers](https://github.com/babel/babel/blob/master/packages/babel-preset-env/data/built-in-modules.json)).

For example:
- `string.split`: [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#Browser_compatibility) it is supported in every modern browser, but Edge is missing in `data.json`
- `string.replace`: [should be supported everywhere](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Browser_compatibility) (except the deprecated argument, which I think should be ignored here), but only chrome is in `data.json`
- `array.sort`: supported everywhere [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Browser_compatibility)
- `web.url`: [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility) all base methods are available in the targeted browsers, but `data.json` targets Chrome >= 63 and Safari >= 12

Would you be open to a PR to `data.json` changing the ones I am seeing polyfied with my app to use the same compat data as MDN? I am not sure I will have the time to go over the full file.
Or am I wrong here, or is MDN wrong? I looked at git blame and `compat-table` and other sources to find if there are any broken implementation which justify the versions in `data.json` but havent been able to find any.

**Comment by nicolo-ribaudo** [comment]
MDN could be wrong, but you can run can check if they are actually needed by running the compat tests (https://github.com/zloirock/core-js/blob/master/CONTRIBUTING.md#updating-core-js-compat-data) in those browsers

**Comment by zloirock** [comment]
In case MDN was right, `core-js-compat` would not be required.

See [`core-js` compat test case](https://github.com/zloirock/core-js/blob/master/tests/compat/tests.js) for each of those features. You always [can run it](https://raw.githack.com/zloirock/core-js/master/tests/compat/index.html) in your engine for a check which modules required.

`String.prototype.split` and `String.prototype.replace` requires the support of related well-known symbols, direct internal `.exec` call, named capture groups.

`Array.prototype.sort` supported everywhere, but not everywhere works completely correct. For example, with passed `null` or `undefined`. Maybe in the future, tests and feature detection will be extended to stable sorting support, like it's required by the latest spec.

`URL` is not supported even in almost all modern engines, so `core-js` feature detection ignore some non-critical errors in browsers implementation.

**Comment by odinho** [comment]
Would it be an idea (as a precursor to "loose" mode, or just for us trying to figure out the "why" of things are included) to list browsers that "should" work in the data, but don't due to bugs?

I'm running:
```
require("core-js-compat")({ targets: require("browserslist")(), filter: /^(es|web)\./  }).targets
```
To get a list of polyfills I'll get. And I'm currently making a "loose" mode manually by removing polyfills. I know for a fact many of them will work fine since we are currently not polyfilling stuff like `URL`, so I'd like to keep the biggest offenders away at least.

I see you often have a `// comment` with the version number that the browser released the not-fully-spec-compliant version already. But it's usually only for browsers that now have a newer version that is spec-compliant. If that comment came in also for currently-buggy browsers that'd be useful.

(Or this might require the same changes as https://github.com/zloirock/core-js/issues/644 -- then ofc this doesn't make sense).
