### ISSUE TITLE
[RegExp] Named Capture groups

### ISSUE THREAD

**Issue by kalvenschraut** [zloirock/core-js#521]
I am receiving an unexpected qualifier error in IE 11 using the following expression which is coming from the RegExp constructor polyfill.

``` javascript 
const pathRegex = /^(?<schema>[-a-z]+)\.(?<table>[-a-z]+)\.(?<fieldPath>[a-zA-Z_[\].0-9]+)$/; 
const regex =  RegExp(`^${pathRegex.source.substring(1,pathRegex.source.length - 1)}#(?<bindingNumber>[0-9]+)$`);
```
I wanted to use pathRegex by itself but the normal regex variable is suppose to be made up of the pathRegex variable. Right now I can work around this by copying it over, but I would prefer to use the variable to construct the whole regex. 

I am using core-js@3 and babel-preset-env@7.4.2
I must say the usage flag recently introduced is making my job of maintaining IE 11 compatibility a lot easier!

**Comment by AlokTakshak** [comment]
@zloirock I would like to contribute , can you tell me what needs to be done?

**Comment by zloirock** [comment]
@kalvenschraut you could find some basic info [here](https://github.com/zloirock/core-js/blob/master/CONTRIBUTING.md). As an example, you could take a look at [`Number` constructor wrapper](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.number.constructor.js) for handling modern number literals.

**Comment by zloirock** [comment]
If you have any more detailed questions - just ask me.

**Comment by AlokTakshak** [comment]
@zloirock I have gone through Number constructor wrapper and RegEx constructor wrapper , but I am not understanding what is the requested change,  do we need to accept a variable and a pattern to construct RegEx instead of only pattern?, please clarify what needs to be implemented.

**Comment by zloirock** [comment]
`RegExp` constructor should parse patterns with NCG syntax and return a regex created from pattern allowed in the old version of the language with internal metadata about NCG. `RegExp.prototype[@@match]` should be patched for creating `groups` property with the required result.

**Comment by zloirock** [comment]
Seems something like here https://github.com/commenthol/named-regexp-groups, but in the main class.

**Comment by AlokTakshak** [comment]
> Seems something like here https://github.com/commenthol/named-regexp-groups, but in the main class.

I have few questions regarding that:-
1. do we have to implement the same thing as implemented  in the above link?
2. why only on `RegExp.prototype.exec` why not on `match`

**Comment by zloirock** [comment]
1. Not exactly - as I wrote, it should return a real regex instance, not something regex-like. It's just an example. Also, you could take a look at related `babel` [transform output](https://babeljs.io/repl#?babili=false&browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=OQRw7gpghgzgJuCwB0BbKAXAxgCwBQD0eA_ADyIB8iAlAQObVA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2016%2Creact%2Cstage-2%2Ctypescript%2Cenv&prettier=false&targets=&version=7.4.5&externalPlugins=) and the [helper](https://github.com/babel/babel/blob/8f8a4577989c472f244f3d439821997622129ed0/packages/babel-helpers/src/helpers.js#L1836-L1906)
2. It theoretically could require changes not only on `RegExp.prototype.exec`, but also in some other methods, for example, on `RegExp.prototype[@@replace]`, but I don't think that on `match` since `String` methods related `RegExp` should call related `RegExp` methods and that should call `RegExp.prototype.exec` under the hood.

**Comment by shtelzerartem** [comment]
@zloirock Due to inactivity, I've decided to make a quick dive into this issue. 
I started working on patching ```regexp-exec.js```.

To check if named groups are not supported: 
```javascript
var NCG_INCLUDED = /()/.exec('').groups !== undefined;
```
After that, it goes to extracting group names from the regexp source, deleting them from there, as after we can make matching with match results by indexes as it's, actually, done in [babel helper reference](https://github.com/babel/babel/blob/8f8a4577989c472f244f3d439821997622129ed0/packages/babel-helpers/src/helpers.js#L1893-L1905). 
But building the regexp query for that comes with trouble because group name is an object property name and should be validated accordingly. I found [this project here](https://github.com/mathiasbynens/mothereff.in/blob/master/js-properties/eff.js), but wanted to take your advice, maybe I'm missing smth?

Would be happy to hear your thoughts about it!

**Comment by zloirock** [comment]
By my understanding, `es.regexp.constructor` should contain detection support of NCG (or it should be in a separate helper), if they are not supported it should extract named groups and transform regexp to supported syntax. If NCG are not supported, `regexp-exec` side should evaluate regexp and match the result with the extract groups. About language characters - I don't know, I didn't check those examples, I'll do it when I'll have enough time.
