### ISSUE TITLE
Doubled packages in webpack-bundle-analyzer 

### ISSUE THREAD

**Issue by mercs600** [zloirock/core-js#522]
Hello ✋ I'm using core js together with vue/webpack/webpack-bundle-analyzer. In the report I see some double packages - I don't know why: 
![Zrzut ekranu 2019-04-1 o 17 14 38](https://user-images.githubusercontent.com/7935392/55338815-bf738e80-54a1-11e9-8bd3-3b16d652d724.png)

It is problematic, because I got doubled sizes of vendor file. 
Could you give me an explanation why it works like that ?

**Comment by zloirock** [comment]
It's obsolete `core-js@2`. With `core-js@3` you will the same result, but instead of `core-js/library` you will see `core-js-pure`. One version of this file here - global polyfill, another - version without global namespace pollution. It could be the same JS files, but with different internal states, different dependencies. It problematically to make it work with one file since it will seriously increase the size of each version. If you wanna reduce your bundle size, you can try to get rid of usage non-global version of `core-js` - for example, you can mistakenly use `@babel/runtime` where it's not required, or add `webpack` mapping `core-js/library` -> `core-js` for usage global version of `core-js` instead of non-global.
