### ISSUE TITLE
Don't use IE11's native `getOwnPropertyDescriptor` on objects like `window.location`

### ISSUE THREAD

**Issue by Hypnosphi** [zloirock/core-js#601]
It throws "Object doesn't support this action" error

See https://github.com/babel/babel/issues/10233  for context

**Comment by zloirock** [comment]
It's not an issue of `core-js`. In your example, `babel` helpers use `Object.getOwnPropertyDescriptor` on `window.location`. They call `core-js` wrapper of `Object.getOwnPropertyDescriptor`, but it's just a wrapper - you will have the same issue in IE11 even without `core-js`. IE11 `Object.getOwnPropertyDescriptor` can't with environment exotic objects like `window.location` and, in the scope of `core-js`, we can't add special cases for all possible environment exotic objects.

Since it's not a `core-js` issue, I'll reopen the issue in the `babel` repo, but I don't think that it's something that should be solved on `babel` helpers side.

If you wanna just copy a URL, you could use just `const locationCopy = new URL(window.location)`.

**Comment by Hypnosphi** [comment]
> If you wanna just copy a URL, you could use just const locationCopy = new URL(window.location)

No, I'm actually extending the object: `{...window.location, ...somethingElse}`

**Comment by zloirock** [comment]
@Hypnosphi you could extend a copied location.
