### ISSUE TITLE
Your job notification

### ISSUE THREAD

**Issue by JasonCubic** [zloirock/core-js#609]
Hey feel free to close or delete this.  If you are serious about wanting help getting a job please include your location.  Developers in that region might know of a spot for you, or notify their recruiters who could contact you.

**Comment by zloirock** [comment]
Thanks. My location makes no sense for this message since I'm looking for remote work with possible relocation in the future. I don't see any companies where I could realize myself in my current region.

**Comment by adelphes** [comment]
HI @zloirock - I know there's been a lot of comments about the inclusion of your job request in the post-install message. I have read the (many!) comments from both sides, but I hoped you would think again about this.

We run builds every day and due to the dependencies in our project, we see your "I need a job" message over and over in our logs. Of course, it does us no real harm (other than making people ignore the output from the logs), but it is leading down a path of "advertising in builds" which is something I doubt anyone wants.

I fully understand that developing and maintaining open-source projects can be extremely time-consuming and, at times, exhausting, but placing personal messages into build logs really isn't useful for developers, or a good advert for yourself. The fact that `core-js` is so widely used should be enough to support any job application.

Obviously there's nothing anyone can do to stop you putting arbitrary messages into your library, but I do hope you reconsider this.

Thanks.
