### ISSUE TITLE
Breaking change in v3.3.0: Node < 8 is not supported anymore by core-js-compat

### ISSUE THREAD

**Issue by nicolo-ribaudo** [zloirock/core-js#669]
Hi :wave: 

57f497de585b291a5bde1e02216406a802771f3c introduced the `engines.node` option in `core-js-compat`'s package.json.
That package already works in node 6, since it uses only these "new" es features, which are supported in node 6
- `for...of`
- `...` spread in function calls
- `Map`/`Set` (iterator closing is not supported)

While that metadata-only change might seem innocuous, it causes `yarn` to fail when installing it:
```
error core-js-compat@3.3.1: The engine "node" is incompatible with this module. Expected version ">=8.0.0". Got "6.17.1"
error Found incompatible module.
```

Would it possible to revert that change and:
1. Set in `engines` a node version which wasn't supported for real (e.g. `>= 6.4.0`, according to https://node.green/)
2. Increase it to 8.0.0 (or higher) in core-js 4
?

**Comment by zloirock** [comment]
Previous versions of this package were not compatible with Node 8-, moreover, with Node 8.3-, since here [was used](https://github.com/zloirock/core-js/commit/5a66505301b64d13f7bcf96b1e9ab55e4ff35fe6#diff-c5bfe6b973564caa499beb7e0e17799e) object spread syntax. Node 6 was available to work only in some cases like loading JSON data. Ok, I'll remove this field.

**Comment by nicolo-ribaudo** [comment]
Thanks!
