### ISSUE TITLE
[V8] Array.prototype.splice ~100x slower in V3 with symbol polyfill

### ISSUE THREAD

**Issue by jimmydief** [zloirock/core-js#677]
This seems like it may be similar to #377. We recently discovered a perf issue after upgrading to v3.2.1 from v2 and tracked it down to a call to `Array.prototype.splice` that was occurring within a loop. Testing the performance of that method in isolation in environments with `core-js/features/symbol` applied revealed a similar issue.

I created [a sample benchmark/repro](https://github.com/jimmydief/core-js-3-splice-perf) that shows the relative performance with different versions.

**Comment by zloirock** [comment]
`core-js@3` add a polyfill of `Array.prototype.splice` with `@@species` support. Yes, it's seriously slower than native implementations. Because of the performance issue, it wasn't added in 2014-2015 when it was possible, but only in this year, when all modern engines suppors `@@species` natively and it's a performance problem mainly for old engines like IE11. Or you have this problem in modern engines?

**Comment by zloirock** [comment]
Hmmm... Interesting example. Seems it's also an issue for modern V8. `core-js` does not replace `Array.prototype.splice`, it's still native, but we have performance degradation. I have no ideas.

Maybe one more kind of engine deoptimizations like #306? cc @schuay

**Comment by jimmydief** [comment]
@zloirock Thanks for the response. I see this behavior in Chrome 77 and Node 12.13.0. The issue seemed to be less significant in Firefox/Safari but the regression is still very much noticeable.

**Comment by zloirock** [comment]
I found the problem place. It's calling of [this test](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/array-method-has-species-support.js). We try to use `Array.prototype.splice` on array with changes `@@species`. Seems V8 sees that we can do something like that and after that uses only a deoptimized version. Yes, it's an equal of #306.

It's V8 bug, not a `core-js`. I don't think that I can do something here because even removing this polyfill will be a breaking change. You could write it to V8 bug tracker.

A solution for your - avoid `core-js/modules/es.array.splice` module (maybe also could be required to disable other methods which use `@@species` on `Array.prototype`, but unlikely). You can do it with `@babel/preset-env`, `useBuiltIns` option and a blacklist.

cc @littledan

**Comment by zloirock** [comment]
If I understood V8 source correctly, it's `IsArraySpeciesProtectorCellInvalid`, so it also affects `Array#{ filter, map }` :-(

**Comment by schuay** [comment]
Recent V8 versions also have a --trace-protector-invalidation flag that might help demonstrate what's going on:

```
out/debug/d8 --trace-protector-invalidation
d8> /./.constructor = () => {}
Invalidating protector cell RegExpSpeciesLookupChainProtector() => {}
```

I would still like to understand why core-js must touch these prototypes / species symbols. Above you said 'removing this polyfill will be a breaking change.' Could you explain (perhaps off-thread since this is slightly off-topic) what the polyfill does and why it must be applied even in recent V8 versions that should already implement the latest version of the spec?

Perhaps we can figure out a way to implement these polyfills without hitting all of V8's slow paths.

**Comment by zloirock** [comment]
@schuay it's a polyfill for feature, which causes this deoptimization (in this case - `@@species` support in `Array#splice`). Without calling this feature (`Array#splice` on an object where `@@species` is not `Array`), we can't determinate is this feature supported or not.

**Comment by zloirock** [comment]
Digging the V8 code, since `Array#splice` is generic, I found a possible workaround - calling `Array#splice` on a usual object with custom `@@species` instead of an array. (Really strange deoptimization 🤦.)

**Comment by mathiasbynens** [comment]
> Digging the V8 code, since `Array#splice` is generic, I found a possible workaround - calling `Array#splice` on a usual object with custom `@@species` instead of an array. (Really strange deoptimization 🤦.)

Anything that avoids changing built-in prototypes ([like `Array.prototype.constructor`](https://github.com/zloirock/core-js/blob/34a8a4d77b8d2daaac3006d1f57b58692b63d93a/packages/core-js/internals/array-method-has-species-support.js#L9)) would certainly help.

**Comment by schuay** [comment]
Yes that certainly helps. We only care about `constructor` and `@@species` on relevant objects. See https://cs.chromium.org/chromium/src/v8/src/objects/lookup.cc?l=235&rcl=4f7ba9bb11d0641bd17655286f81106544790479. 

E.g. for `IsArraySpeciesLookupChainIntact`:
- `constructor` modifications on an array or the array prototype
- `@@species` on the Array function.

**Comment by zloirock** [comment]
@mathiasbynens in this case, we do not change built-in prototypes, we change `.constructor` property on an instance.

`core-js` is a polyfill - its job is to add or to change something on built-in prototypes :-D

**Comment by zloirock** [comment]
@schuay but since `RegExp` methods are not generics - this approach will not work for them...

**Comment by schuay** [comment]
> core-js is a polyfill - its job is to add or to change something on built-in prototypes :-D

The point is not to make these changes only when needed, i.e. not during feature detection.

**Comment by zloirock** [comment]
@schuay we don't do it on feature detection.

**Comment by zloirock** [comment]
@schuay I know, I wrote it above, I already wrote a workaround.

**Comment by schuay** [comment]
> @schuay I know, I wrote it above, I already wrote a workaround.

Sounds great :+1: 

> @schuay but since RegExp methods are not generics - this approach will not work for them...

I'm not sure what you mean by generics, but RegExp methods do support subclassing. E.g. `RegExp.prototype.test` can be called on any object that has an `exec` method. https://tc39.es/ecma262/#sec-regexp.prototype.test

**Comment by zloirock** [comment]
@schuay not all `RegExp` methods are generics, only a part of them (and, if I understood correctly, which not required for us) allows doing something like in the workaround above. I'll dig it later, maybe it's possible...

**Comment by schuay** [comment]
> @schuay not all `RegExp` methods are generics, only a part of them (and, if I understood correctly, which not required for us) allows doing something like in the workaround above. I'll dig it later, maybe it's possible...

Feel free to ping me via email or on the tracker.

**Comment by zloirock** [comment]
Seems I closed it too early. `ArraySpeciesCreate` creates instances of `@@species` only it's called on array, so it's not generic. The feature detection does not work, I should revert it. Any ideas of how I can detect it without deoptimization?

**Comment by zloirock** [comment]
Sure, we can just detect the engine version and do not call feature detection in modern V8, but it is a very bad practice...

**Comment by schuay** [comment]
Not sure I understand the second point, are you asking if the Proxy-based solution could somehow cause a global switch to flip to the slow path in other engines? 

If so, anything is possible I guess.. But I think it's very unlikely given that no global state is modified in the proxy-based solution.

**Comment by zloirock** [comment]
@schuay yep, something like that.

Let's think about alternative solutions for tomorrow - maybe we could find something better - and if not let's apply one of the mentioned above.

**Comment by zloirock** [comment]
I added engine version detection and not calling this feature detection in modern V8. If feature detection or usage of `Proxy` will be required for any other case, I'll move it to the version, proposed by @schuay.

**Comment by jimmydief** [comment]
Thanks, benchmark results confirm that this worked!

**Comment by schuay** [comment]
Thanks! Are you planning to do something similar for other builtins, especially `RegExp`?

**Comment by MargaretKrutikova** [comment]
I experienced the same issue with `v3` in Internet Explorer 11, but not in other browsers, so we had to rollback to `v2` because IE 11 was completely frozen.

Is it a known issue or has anyone else experienced the same? 
Appreciate any help on this, since we are currently stuck on the legacy `core-js` `v2` and can't upgrade because we have to support IE 11.

**Comment by Slapbox** [comment]
@slowcheetah could you provide some idea of what's going on with this issue? I'm confused about whether or not this is fixed.

**Comment by zloirock** [comment]
> I experienced the same issue with v3 in Internet Explorer 11, but not in other browsers, so we had to rollback to v2 because IE 11 was completely frozen. Is it a known issue or has anyone else experienced the same?
Appreciate any help on this, since we are currently stuck on the legacy core-js v2 and can't upgrade because we have to support IE 11.

It's definitely not this error. Without any additional information, I can't say anything.

**Comment by jdalton** [comment]
I filed a V8 bug on this as I was recently bit by this, in a different project, as well  https://bugs.chromium.org/p/v8/issues/detail?id=13202
