### ISSUE TITLE
Did the author of core-js ever find a good job?

### ISSUE THREAD

**Issue by jannik-mohemian** [zloirock/core-js#708]
👋 I'm interested in whether you ever found a good job through the post-install message - it's been a while since this all started...

**Comment by davalapar** [comment]
`good-first-issue`

**Comment by zloirock** [comment]
Dear @jannik-mohemian, no, I still have not found a good job, otherwise, this part of the message will be removed. Please, use the search, since you could find the answer in [other issues](https://github.com/zloirock/core-js/pull/642#issuecomment-552430990).

**Comment by fuzzy76** [comment]
TBH, I'd think twice about employing someone that would use tactics like this. It might be wanted by some, what do I know... 🤷‍♂️ But for me, it's a red flag.

**Comment by mistercrunch** [comment]
Can we reopen this issue until @zloirock is happily employed?

**Comment by benjaffe** [comment]
Advertising in everyone's terminal in bright teal is probably the best strategy to gain bad notoriety. As a fun bonus, it marginally decreases the entire industry's productivity as people discuss this rather than work. I know I've personally lost time to it writing something to filter the hundreds of non-deduped ads out.

**Comment by manavm1990** [comment]
@zloirock is doing great to promote and folllowing the axios, "Ask and you shall receive." There is no 'red flag' for me @fuzzy76 - it's a green flag - he put in time and effort to build something that companies that are hiring are probably using. Good for him.

**Comment by ELI7VH** [comment]
found a job yet? :)

**Comment by KartikChugh** [comment]
Did the buddy find his job yet

**Comment by KartikChugh** [comment]
Buddy is waiting in the unemployment line eh

**Comment by fuzzy76** [comment]
He is in prison. See #767

**Comment by manavm1990** [comment]
I do see some talk on that. Would be interested in the whole story, but folks go to prison for all kinds of things - sometimes justifiably, sometimes accidentally, sometimes completely unjustified.
Depending on the circumstances and considering his indirect contribution to...basically my job and revenue as for others, I for one would consider donating to legal fees if it would help.

**Comment by delanni** [comment]
I love how poor slowcheetah's work these days must be 50% closing issues and requests related to zloirock's desperate attempt to find a good job -)

**Comment by parzhitsky** [comment]
Plot twist: @slowcheetah is an elaborate fake account created by @zloirock

**Comment by manavm1990** [comment]
Ugh! Well now you blew it! ;) This guy might need his own short biopic at this point!

**Comment by manavm1990** [comment]
https://github.com/zloirock/core-js/issues/833#issuecomment-717107661 Well, I guess he's out. 🤷 . Good for him, either way.

**Comment by Muhammad-Bilal-7896** [comment]
> Dear @jannik-mohemian, no, I still have not found a good job, otherwise, this part of the message will be removed. Please, use the search, since you could find the answer in [other issues](https://github.com/zloirock/core-js/pull/642#issuecomment-531202604).

Sir I am so much confused how can the expert like you dosent have a good job.Its really surprising and sad please give details.

**Comment by caihongxu** [comment]
Maybe the reason no one is offering him a job is because his current job is so much more important and he is doing good at it? For anyone who benefited from his work, the apparent thing to do would be donation, not offering him a full time job because otherwise who knows what will happen to core js?

**Comment by Muhammad-Bilal-7896** [comment]
Yes donation must be done for that.

**Comment by VictorQueiroz** [comment]
@caihongxu If you're right, apparently he's not interested in maintaining core-js and only keeps maintaining so he can advertise his long search for a "good" job. Otherwise, why would he ever advertise that if he's interested in donations? Maybe people shouldn't be relying on him to keep `core-js` alive.

**Comment by manavm1990** [comment]
I haven't seen it for a while. I guess I am no longer using this package, somehow. I do still want to know though!

**Comment by zloirock** [comment]
Seems you missed this https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
