### ISSUE TITLE
core-js-pure leaking __core-js_shared__ to the global space

### ISSUE THREAD

**Issue by kaidjohnson** [zloirock/core-js#726]
First off, core-js w/ babel (via preset-env or transform-runtime) has become an integral solution to our cross-browser implementations, and I cannot express how awesome it is for this library, and the folks that maintain it, to exist. A big thank you!

I was confused for a while around the differences between using preset-env and transform-runtime, but once I realized they should not be used together to apply corejs via babel, things started clicking a lot more. The transform-runtime uses core-js-pure under the hood, which, as far as I understand it now, is meant to prevent core-js polyfills from polluting the global scope. While our initial migration from preset-env to transform-runtime was very positive (no more global Promise pollution, etc), we were still seeing a strange side effect when our library was deployed to third-party websites. It took some digging, but we finally isolated the issue as both the website and our library were sharing a common global `__core-js_shared__` object. Our library and the website probably do not share the same versions of babel, webpack, or even core-js, and we do not have control over the website in question.

I cannot find any documentation around `__core-js_shared__`, so I'm not 100% sure if this issue is a bug, but I would expect `core-js-pure` _not_ to use a global shared object due to not polluting the global scope by design. 

We have been able to work around the issue by setting up a rule that includes `/core-js/` with the string-replace-webpack-plugin to replace `__core-js_shared__` with a unique value.

Our configuration:

@babel/core: 7.7.5
@babel/plugin-transform-runtime: 7.7.6
@babel/preset-env: 7.7.6
@babel/runtime-corejs: 7.7.6
webpack: 4.41.2

```
module.exports = {
	sourceType: 'unambiguous',
	presets: [
		['@babel/preset-env', {
			loose: true, // IE8
			modules: 'commonjs' // IE8 @see https://github.com/webpack/webpack/issues/6979#issuecomment379414342
		}]
	],
	plugins: [
		['@babel/transform-runtime', {
			corejs: 3
		}]
	]
};
```

**Comment by zloirock** [comment]
It's expected behavior. Too often projects use many copies of `core-js`, methods / constructors from they should interact together, they should use compatible protocols. For example - well-known symbols, for example - `@@iterator`. Iterables from one `core-js` copy should work with methods that accept iterables in another. If you use some `core-js` copies which do not modify built-ins, `Symbol.iterator` will not be exposed. Without any shared state, they will not work together. So `__core-js_shared__` which contains the shared state like well-known symbols and some debugging info is an acceptable compromise.

**Comment by kaidjohnson** [comment]
I completely agree for standard usage of `core-js`, however I'm not sure I agree that `core-js-pure` should participate in this sharing. By definition, isn't `core-js-pure` supposed to sandbox its implementation to prevent global pollution? Any self-contained library that is designed to be deployed to a variety of websites that is intended to be safe from global conflicts shouldn't participate in any shared global definitions.

In our case, we're seeing a website with core-js@2.5.7 deployed with our library containing core-js-pure@3.5.0 affecting functionality on the website (in IE11), even though our bundle isn't configured to run on the site and effectively a noop. When we rewrite the `__core-js_shared__` value to a unique value and redeploy the same library, the website is unaffected and functions properly. This observation suggests that the shared object may not be working as desired for browsers that apply core-js polyfills, at least across core-js versions and modes.

<img width="471" alt="Screen Shot 2019-12-12 at 11 41 28 AM" src="https://user-images.githubusercontent.com/565754/70731549-df1bb180-1cd4-11ea-80c2-338f6ac9ace3.png">

**Comment by zloirock** [comment]
It's required **only** because of the pure `core-js` version, for the version that can modify global built-ins it's not required since in our example with `@@iterator` we can expose global `Symbol.iterator`. With full isolation, different `core-js-pure` copies will not work together and with the global `core-js` version. As I wrote, you should not have any conflicts. If you have it - please, write an issue with details or, better, with a reproducible example.
