### ISSUE TITLE
Array.prototype[Symbol.unscopables] polyfill change breaks some code

### ISSUE THREAD

**Issue by lwr** [zloirock/core-js#733]
I had read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@unscopables and do not find any mentions about behavior of `toString`

Testing codes
```js
[][Array.prototype[Symbol.unscopables]]
// chrome            -> TypeError: Cannot convert object to primitive value
// IE8 - core-js@2   -> undefined
// IE8 - core-js@3   -> TypeError: Object doesn't support this property or method

Array.prototype[Symbol.unscopables].toString()
// chrome            -> TypeError: Array.prototype[Symbol.unscopables].toString is not a function
// IE8 - core-js@2   -> "[object Object]"
// IE8 - core-js@3   -> TypeError: Object doesn't support this property or method

`${Array.prototype[Symbol.unscopables]}`
// chrome            -> TypeError: Cannot convert object to primitive value
'' + Array.prototype[Symbol.unscopables]
// IE8 - core-js@2   -> "[object Object]"
// IE8 - core-js@3   -> ""
```

we have some legacy code like this
```js
var OPTIONS = ['foo', 'bar'];
for (var i in OPTIONS) {
    var option = OPTIONS[i];
    if (src[option] !== undefined) {
        target[option] = src[option];
    }
}
```
we actually know it is totally wrong code but just worked in core-js@2 and now it throws TypeError when testing `src[option]` for a hidden call with `toString`

The question is, is that behavior throw error for toString call is required?

**Comment by lwr** [comment]
More test
```js
Array.prototype[Symbol.unscopables].__proto__
// chrome            -> undefined
// IE8 - core-js@2   -> undefined
// IE8 - core-js@3   -> undefined
```

**Comment by aleen42** [comment]
```js
[][Symbol.unscopables] instanceof Object;
// chrome  -> false
// IE8 - core-js@2  -> true
// IE8 - core-js@3  -> false
```

**Comment by aleen42** [comment]
Is there any plan for implementing `__proto__` under IE8? @zloirock

**Comment by zloirock** [comment]
@lwr `Array.prototype[Symbol.unscopables]` is non-enumerable property, object with `null` prototype. [Spec](https://tc39.es/ecma262/#sec-array.prototype-@@unscopables), [`core-js` implementation](https://github.com/zloirock/core-js/blob/6929d43b0e0eaafe06cd4e7e7f4dceb2ee85ecff/packages/core-js/internals/add-to-unscopables.js#L8-L12) - it's implemented properly. It will cause code like your could cause problems only in IE8-, but anyway here it's broken. If you have problems in more modern - it's caused by something else.

@aleen42 see #459. It can't be properly implemented even in IE10.
