### ISSUE TITLE
IE 11 + core-js@3.6.1： String.prototype.split doesn't work correctly

### ISSUE THREAD

**Issue by bloody-ux** [zloirock/core-js#741]
With core-js 3.6.1: '/home/sessionCheck.json'.split(/\/+/) will get:

![image](https://user-images.githubusercontent.com/19991767/71653053-5d63f480-2d65-11ea-8d7a-99fb45adbb25.png)

The correct result should be: 
![image](https://user-images.githubusercontent.com/19991767/71653075-77053c00-2d65-11ea-93e9-5a3b8a8f3ba7.png)

**Comment by zloirock** [comment]
In which engine? How do you import `core-js`?

**Comment by randym** [comment]
@zloirock @bloody-ux 

I was able to reproduce this in a browserify/babelify build when @babel/preset-env useBuiltIns is configured to 'usage' which adds the following core-js polyfills to the module doing a split with a regular expression.

```
  es.regexp.exec { "ie":"11" }
  es.string.split { "edge":"18", "ie":"11" }
```

In the short term, there where two ways I was able to work around this.

1. Downgrade core-js to 3.5.0

2. set useBuiltIns to 'entry' (assuming you are not importing core-js manually)

**Comment by zloirock** [comment]
@randym I tested this case too. Could you add a reproducible example?

**Comment by randym** [comment]
@zloirock I've setup a repo to start pulling in the polyfills that my client's app used and see if I can reproduce it in a 'bare-ish' bones example. 

Just pulling in
```
es.regexp.exec { "ie":"11" }
es.string.split { "edge":"18", "ie":"11" }
```

In isolation was not enough to reproduce the problem.

I've sent both of you collaborator invites with the understanding that @bloody-ux and I bare the burden of reproduction.

**Comment by zloirock** [comment]
Still the same with the example from your repo:
![image](https://user-images.githubusercontent.com/2213682/71684569-76ea5800-2dc8-11ea-99f8-aebe6129049f.png)

I have no ideas about the order which could cause the problem, so waiting for that.

Seems it's caused by #732, I thought about possible problems like this, but I didn't find them.

**Comment by asapach** [comment]
I was able to reduce the problem to:
```js
import 'core-js/stable/string/split';
```
Once the regexp polyfills are included the problem goes away:
```js
import 'core-js/stable/regexp';
```

**Comment by zloirock** [comment]
@asapach I can't find the problem in the code, however, that makes sense, I'll check it in IE11 little later. But in the @randym issue `es.string.split` injected **only** with `es.regexp.exec`.

**Comment by zloirock** [comment]
Could you check it with this patch?

**Comment by asapach** [comment]
I've checked the fix and it does seem to address the problem in my use case.

**Comment by randym** [comment]
confirmed fix @zloirock / @asapach - thanks

**Comment by albert-asin** [comment]
I have the same problem with IE11 + core-js 3.6.5 + D3 + angular 9
I cannot downgrade to core-js 3.5.0 
so, I found a workaround

I replaced the following line in my polyfills.ts
import 'core-js';

to
import 'core-js/stable/array';
import 'core-js/stable/date';
import 'core-js/stable/function';
import 'core-js/stable/map';
import 'core-js/stable/math';
import 'core-js/stable/number';
import 'core-js/stable/object';
import 'core-js/stable/parse-float';
import 'core-js/stable/parse-int';
// import 'core-js/stable/regexp';
import 'core-js/stable/set';
// import 'core-js/stable/string';
import 'core-js/stable/symbol';
import 'core-js/stable/weak-map';

Note that the imports regexp and string are commented. 

So when your application needs to do a split it's using the native function of the browser instead of the split function in core-js

I hope this can help someone

**Comment by artem1** [comment]
Same problem on core-js 3.8.1
@babel/preset-env with ie11 and useBuiltin: usage

![image](https://user-images.githubusercontent.com/4537619/102317005-f21c2e00-3f87-11eb-9db3-99398d525846.png)


![image](https://user-images.githubusercontent.com/4537619/102317102-0d873900-3f88-11eb-8e4f-f845cfda2869.png)


And also can't repro without all code...

This regexp in superagent lib (parse http request headers), can't patch in lib ((

**Comment by artem1** [comment]
downgrade to core-js 3.5.0 helps (no es.string.split module in bundle now)

**Comment by Jokero** [comment]
With downgraded version I get an error related to promise: "Object doesn't support property or method 'allSettled'"
