### ISSUE TITLE
IE11 + core-js@3.6.4 String.prototype.split doesn't work with regexp

### ISSUE THREAD

**Issue by kmsheng** [zloirock/core-js#751]
<img width="704" alt="Screen Shot 2020-01-15 at 9 40 26 PM" src="https://user-images.githubusercontent.com/880569/72438430-c32d9300-37df-11ea-9d16-d246cb5469c1.png">

repo to reproduce
https://github.com/kmsheng/core-js-bug

Note that core-js was imported twice,
one in src/js/index.js and the other one in assets/js/default.js

simlar issue
https://github.com/zloirock/core-js/issues/741

**Comment by jaynetics** [comment]
i encountered the same bug, and can confirm that importing core-js into two js files is the root cause. importing it in only one file fixes the problem.

**Comment by 11101101** [comment]
I'm also running into the same issue. My code path results in a second import which causes the bug to manifest.

**Comment by pierremanceaux** [comment]
In case this helps someone: https://github.com/github/fetch/issues/748
It would be great to identify which version of IE11 is/are affected, but it seems pretty recent to me, probably the last build.

**Comment by aliaksandr-yermalayeu** [comment]
Hi everyone. I am facing the same issue. It is still reproduced in IE11 with the latest version of core-js. However the scenario is pretty tricky to reproduce. So I created a[ minimal repo](https://github.com/aliaksandr-yermalayeu/core-js-ie-bug) with needed steps. Hope it helps.

**Comment by sargismarkosyan** [comment]
Hi, the issue is reproducible with other regexp too for example `'/test/'.split(/\W/)` is returning `["/", "t", "e", "s", "t", "/"]` but should return `["", "test", ""]`.

**Comment by slowcheetah** [comment]
Please show your `npm list | grep core-js`

**Comment by aliaksandr-yermalayeu** [comment]
@slowcheetah, will result of `yarn list --pattern core-js` work for you?
```
├─ core-js-compat@3.6.4
└─ core-js@3.6.4
```

**Comment by aliaksandr-yermalayeu** [comment]
I took a deeper dive into this issue. The problem is caused by this [line](https://github.com/zloirock/core-js/blob/f10bf27fa665cde29e549262da977946557c84b4/packages/core-js/internals/fix-regexp-well-known-symbol-logic.js#L81). It turns out `regexp.exec` and `regexpExec` are different references when polyfill is loaded twice.

**Comment by steveworkman** [comment]
Is there an older version of core-js that does not show this issue? It looks like there were changes related to adding more regexp.exec requires in [3.6.2](https://github.com/zloirock/core-js/commit/bccbad74906d20a44121fef894e5c87a325b6734)
Would a downgrade to 3.6.1 work?

**Comment by jdreesen** [comment]
I downgraded to `3.5.0` yesterday and it works for me.

**Comment by aliaksandr-yermalayeu** [comment]
The bug was [introduced by version 3.6.0](https://github.com/zloirock/core-js/commit/80d7bfee5e5974f4e5c591c80b0aff8362daf4e1#diff-366a2f3e7698b3133c59b0ea0c944a2fR26) due to support of `y` flag. In version 3.5.0 `exec` was never patched in IE.

**Comment by toxik** [comment]
is reverting the sticky flag support considered?

**Comment by slowcheetah** [comment]
@toxik Not yet. But I think about it, because I can’t make it work correctly and break nothing

**Comment by toxik** [comment]
@slowcheetah have you got any news regarding a revert/fix ? thanks

**Comment by toxik** [comment]
you can upgrade XRegExp to v4.4.0 instead – https://github.com/slevithan/xregexp/issues/300

**Comment by scrollbar-ww** [comment]
same problem with 3.8.0.
I  put a .replace() before call String.split() as a short term fix  :
`str.replace(someRegexp/g, ' \n').split('\n')`

**Comment by Jokero** [comment]
@slowcheetah Are there any plans to rollback sticky flag?

**Comment by zloirock** [comment]
@Jokero sticky flag will not be reverted. Feel free to work on exploring and fixing this issue without it.

**Comment by Khartir** [comment]
I looked into this a bit. As far as I can tell  the issue lies in the way `regexp-exec` (which is required by `string.split`) provides the patched `exec`-function. It creates a new patched function, if `regexp-sticky-helpers.UNSUPPORTED_Y` is `true`.

In order for `UNSUPPORTED_Y` not to be `true` the `regexp.constructor` and `regexp.sticky` polyfills are required.

However, these are not included with `regexp-exec`, so unless they are explicitly included `regexp-exec` provides a new patch-function if called in separate files.

So I think the solution would be for `regexp-exec` not to use `UNSUPPORTED_Y` to check for support but instead to ensure `sticky`-support exists requiring `regexp.constructor` and `regexp.sticky`.

@zloirock Do you agree? I can try to provide a PR for this, but I am unsure how to do this correctly. Should I use a simple `require` or is there another way for one polyfill to ensure the presence of another polyfill?

I assume a similar issue could exist with `regexp.flags` but I have not tested this.

**Comment by zloirock** [comment]
@Khartir sounds reasonable, you could try to add a PR. I don't think that it could affect `.flags` - it's an unrelated case.

**Comment by marcospont** [comment]
My team just experienced this issue because we were running core-js 3.9.1 in our code.
Because of the above mentioned issue, one other library we are using to polyfill CSS variables (css-vars-ponyfill) was producing severe performance issues. The execution time of variables polyfilling was more than 200 seconds when it should be around 5. :)
