### ISSUE TITLE
chrome mobile 30.0.0: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aladdin-add** [zloirock/core-js#752]
![image](https://user-images.githubusercontent.com/13050025/72510703-df374000-3884-11ea-9998-638aa96d0af6.png)

core-js: 3.6.2
browser: Chrome Mobile 30.0.0

this might be related to 2 polyfills loaded:[js-polyfills](https://www.npmjs.com/package/js-polyfills)

**Comment by slowcheetah** [comment]
> this might be related to 2 polyfills loaded:js-polyfills
looks like this

Why are you using js-polyfills?

**Comment by aladdin-add** [comment]
I agreed it's a rare case; it just happened in an old project( I'm not the author) (ノへ￣、)

**Comment by JakeChampion** [comment]
js-polyfills has it's own Symbol polyfill and so does core-js. You can't combine those two polyfill libraries together because they only work with their own Symbol polyfills, that is because it is impossible to make a perfectly spec-compliant Symbol polyfill, so all other polyfills which rely on Symbol (such as `Array.from` or `RegExp.prototype[@@replace]()` etc) rely on a specific Symbol polyfill to exist.

You can see this is the case because the errors you are seeing are to do with fixing the well-known Symbols.

**Comment by aladdin-add** [comment]
thanks for the response!
I've fixed it by removing js-polyfills, so closing!
