### ISSUE TITLE
postinstall script forces package to become unplugged with yarn pnp

### ISSUE THREAD

**Issue by DuBistKomisch** [zloirock/core-js#758]
WIth yarn 2 about to become stable, it comes with pnp enabled by default, so postinstall scripts now have one more downside. Having a postinstall script forces `core-js` to be duplicated on disk unnecessarily, reducing the efficiency of `yarn install` in pnp mode, which could otherwise potentially perform no writing to disk.

I know you don't want to remove the postinstall script, but just pointing this out. Perhaps we can get yarn to add an explicit `unplugged: false` option to `package.json`?

**Comment by nkalinov** [comment]
Just found out that you can overcome this by explicitly tell Yarn2 not to build the package by adding `dependenciesMeta` to your `package.json` file:
```
{
  ...
  "dependenciesMeta": {
    "core-js": {
      "built": false
    }
  }
}
```
More info here: https://yarnpkg.com/configuration/manifest#dependenciesMeta

**Comment by zloirock** [comment]
Thanks for the issue. However, at first, it's a `yarn` issue since it requires actions on their side - I think it will be better to open this issue in their repo. I don't use `yarn` by myself and I don't want to try to convince `yarn` team of anything. If it will be possible to fix it on `core-js` side, for example, by adding an option in `package.json` - ask me and I will add it.
