### ISSUE TITLE
Promise .then().catch().then() chaining not working in IE11

### ISSUE THREAD

**Issue by anking** [zloirock/core-js#768]
I have a problem with the IE11... again

when i try to do some async task i do show a preloader in certain cases

so my code will be like
```
showPreloader()                 //to show my custom preloader
fetch(...)                      //initiate request to server
.then(...do some actionhere...)
.catch(console.log)             //log errors if any
.then(hidePreloader)            //hide my custom preloader
```
The deal here is that regardless if the promice fails or not i want second .then() to fire. Kinda like finally clause in C#

And of course this works in any browser except IE. This beast breaks chain after the catch() if it happens and my preloader stays on indefinelty. So is there a way to fix this so it works in IE as well?

**Comment by rphilipp64** [comment]
I'm not affiliated with core-js, but I spotted some things in your pseudo code. The listing above does not handle any exception that occurs in the `.catch` callback, simply because is not handled by your "final" `then( hidePreloader )`. If you want to keep using `then` the simplest solution is to pass `hidePreloader` as a second argument too, so it is invoked in case of an error on `console.log` too. Note that this will effectively suppress any errors and always resolve the last Promise in the chain. This may not be desired.

As you state you want something akin the C# finally block ([which also exists in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#The_finally-block)), and I'd say that for your situation it seems more suited to use. There is a [Promise.prototype.finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally), which will always call the callback and also preserve the resolve/rejection state of the Promise it chained off.

In the past I have observed that some browsers do not like the `console` methods being called out of context, which you are effectively doing by passing it as `catch` handler. This may be the error you are running into with IE11? (I haven't verified this). Your code may also run into a synchronous error if the global `console` is not defined, so it may be safer to use this as a `catch` handler:

```
fetch( … )
.then( /*success handler*/ )
.catch( _error =>
{
    if ( typeof console !== "undefined" )
        console.error( _error ); // or console.log, console.error stands out more
    // Your sample is coercing the Promise returned by catch to resolve with undefined.
    // Re-throw the error if you want to propagate the rejection of the fetch call,
    // or any exception in your then handler.
    // Of course, if that error suppression is desired, leave this out.
    throw _error;
} )
.finally( hidePreloader );
```

I'm curious if that fixes your Internet Explorer troubles.

**Comment by slowcheetah** [comment]
@anking It seems like you have icorrect code. In my IE 11 promise.then().catch().then() works fine.
Check your catch section. If an exception is thrown, then there will be sent to the closest catch(), not closest then().
Try that:
```
fetch()
  .then()
  .catch(console.log)
  .then(hidePreloader)
  .catch(alert(error))
```
If you get an alert, then you have exception in catch section with console log. Then you may try somthing like:
```
fetch()
  .then()
  .catch(error => {
    if (typeof console !== "undefined" ) console.error(error);
  })
  .then(hidePreloader)
```
