### ISSUE TITLE
stable sort 

### ISSUE THREAD

**Issue by graingert** [zloirock/core-js#769]
https://github.com/tc39/ecma262/pull/1340

**Comment by zloirock** [comment]
I'm thinking about it, but I'm still not 100% sure.

Feature detection of stable sort requires sorting of arrays and typed arrays (both) with more than 512 elements - many engines use unstable sorting only with arrays larger. Since complexity can be `O(n^2)`, it's up to 513 * 513 * 2 iterations on feature detection - some additional milliseconds on `core-js` loading. Sure, we can detect browser version by UA, but it's not something ultimate.

Which sorting algorithm could be better for implementation? I don't think that something complex is required for obsolete engines.
