### ISSUE TITLE
IE11: Calling delete on 'includes' is not allowed in strict mode

### ISSUE THREAD

**Issue by fbarbare** [zloirock/core-js#844]
Hello,

There seems to be a bug when running core-js on IE in strict mode:
![image](https://user-images.githubusercontent.com/5055248/86816789-2bb54880-c07c-11ea-8f37-e4178b56b9d3.png)

It happens here when importing "includes" for Arrays:
https://github.com/zloirock/core-js/blob/76d9bf50b1b15439366af92885c5a7a1d0ad61c6/packages/core-js/internals/redefine.js#L25

to reproduce it you can:
- Create a new CreateReactApp project
- Install the `auth0-spa-js` library that includes `core-js`
- Import `import { Auth0Client } from '@auth0/auth0-spa-js';` in the main index.js file
- Run `npm start` and open the app on IE

**Comment by JakeChampion** [comment]
Looks like an issue in `auth0-spa-js` because the `core-js/packages/core-js/internals/redefine.js` file does not run in strict mode.

I would presume `auth0-spa-js` is doing a bad bundled distribution whereby they place all `require`s into a single function scope and have that function in strict mode.

Looking at their npm code, it does look like that is the case. You need to open an issue on their repo as this is not a core-js bug -- https://unpkg.com/browse/@auth0/auth0-spa-js@1.10.0/dist/auth0-spa-js.development.js

**Comment by zloirock** [comment]
Rather, I think, it's an issue with an alternative incorrect 3rd party polyfill which defined as non-configurable and which does not pass `core-js` feature detection. `core-js` tries to fix it, but can't delete the previous implementation.

Anyway, it's not a `core-js` issue.
