### ISSUE TITLE
Some Qunit.skip tests fail on Chrome

### ISSUE THREAD

**Issue by yanyan155** [zloirock/core-js#918]
Steps to reproduce:
- go to the file `<project folder>\tests\tests.js`
- change string 
`QUnit.skip('Unhandled rejection tracking', function(assert){`
to string
`QUnit.test('Unhandled rejection tracking', function(assert){`
- comment line 
assert.expect(4)
, so tests will fail on Promise, not on this line
- run `<project folder>/tests/karma.conf.js` via runner (pinner image)
- go to Chrome (my version is Version 89.0.4389.82) and open `http://localhost:9876/` then click debug.
- open developer console -> go to Sourses  tab -> find file `base/tests/tests.js` -> find test by string: `'Unhandled rejection tracking'`
- Error on string: `$promise = Promise.reject(42);` also in pinned image

Will there some plans to fix it?

![erro56r](https://user-images.githubusercontent.com/11044973/111468048-327d7a80-8736-11eb-8bd5-e7c315db7198.jpg)

![karma-konfig](https://user-images.githubusercontent.com/11044973/111468031-2d203000-8736-11eb-9b45-427105c86ca7.png)

**Comment by zloirock** [comment]
[It's the bug of native Chrome `Promise`.](https://bugs.chromium.org/p/v8/issues/detail?id=4874&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Component%20Stars%20Opened&q=Promise&can=1&start=200) In the issue is an incorrect conclusion, but it doesn't change the place where it is. Sure, I could replace native Chrome `Promise`, but I don't think that it's required.
