### ISSUE TITLE
core.min.js error in Safari 8.0.7

### ISSUE THREAD

**Issue by blopker** [zloirock/core-js#92]
It looks like the minifier used is violating the 'use strict'; directive. File used: https://raw.githubusercontent.com/zloirock/core-js/master/client/core.min.js

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <script src="./core.min.js"></script>
</body>
</html>
```

Results in : `SyntaxError: Cannot declare a parameter named 'k' as it shadows the name of a strict mode function. core.min.js:8`

Unminified version works fine.

Cheers! :beers:

**Comment by zloirock** [comment]
It's old safari bug - wrong strict mode rule. Looks like problem in minification, [I thought it was fixed in `uglify` a long time ago](https://github.com/mishoo/UglifyJS2/issues/326). After rebuild w/o any serious changes `core.min.js` works in Safari. I'll publish patch release little later.

\cc @mishoo

**Comment by blopker** [comment]
Great, I'll give it a go when it's released! 

Ah, Safari; The new IE.

**Comment by zloirock** [comment]
I disable compression function names, it should prevent this problem. Available [`1.0.1`](https://github.com/zloirock/core-js/releases/tag/v1%2C0%2C1).

**Comment by blopker** [comment]
I can confirm this is fixed. Thank you!

**Comment by zloirock** [comment]
Thanks for report :)
