### ISSUE TITLE
cant specify { corejs: version, proposals } with babel/runtime

### ISSUE THREAD

**Issue by noahehall** [zloirock/core-js#946]
the readme says i should be able to do this, t get all the sweet goodiness.

[link to babel config](https://github.com/noahehall/nodeproto/blob/dev/apps/client/lib/babel.config.mjs)

```sh
[start:dev] Error: [BABEL] The `core-js` version must be false, 2 or 3, but got "3.14". (While processing: "/super/hidden/paths/@babel/plugin-transform-runtime/lib/index.js")
```

**Comment by zloirock** [comment]
Yes, unlike `preset-env`, the actual version of `transform-runtime` accepts only the major `core-js` version (so at this moment you should use just `3`) and does not adds features added in minor `core-js` releases. Since `transform-runtime` was moved to `babel-plugin-polyfill-corejs3`, it can be simply fixed. Seems it the issue for the Babel repo.

**Comment by zloirock** [comment]
By the way, about your config - you should use `corejs` option only in one place - or in `preset-env`, or in `ransform-runtime`, they should not be used together.

**Comment by noahehall** [comment]
thank you @zloirock
