### ISSUE TITLE
Array.lastIndex polyfill contains no `set` accessor

### ISSUE THREAD

**Issue by overly-engineered** [zloirock/core-js#968]
The proposal for `Array.prototype.lastIndex` as defined [here](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.array.last-index.js) contains both get and set accessors.

The polyfill implemented here contains only the get accessor https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.array.last-index.js.

Can I either update this polyfill to include a setter as well or as the proposal is now paused can I remove the current lastIndex polyfill as it is unlikely to be moved on further.

**Comment by zloirock** [comment]
As you can see [in the spec draft](https://github.com/tc39/proposal-array-last#specification), `.lastIndex` should be only a getter, so the `core-js` implementation is correct.

I'm not sure will this proposal be available in `core-js@4` or not because of the current state of the proposal, will see it later.
