### ISSUE TITLE
TypeError: forEach is not a function in a HTMLCollection

### ISSUE THREAD

**Issue by ahuegle** [zloirock/core-js#989]
`const all = document.querySelectorAll('*')
    console.log('all', all)
    all.forEach(it => console.log(it)); // works
    const divs = document.getElementsByTagName('p')
    console.log('divs', divs)
    divs.forEach(div => {
        console.log('div', div) // error
    });`

second forEach gives an error although debug notes says the polyfills are included:

Added following core-js polyfills:
  es.array.for-each { "ie":"11" }
  web.dom-collections.for-each { "ie":"11" }

Happens with babel7, webpack or rollup.

**Comment by zloirock** [comment]
`HTMLCollection` haven't a `.forEach` method by the standard. In some old `core-js` versions it was added because of a bug, but [it was never documented](https://github.com/zloirock/core-js#iterable-dom-collections). `core-js` adds `.forEach` only to `DOMTokenList` and `NodeList` from DOM collections.

**Comment by ahuegle** [comment]
Ok, thx, i see it in release notes 3.18.1.
We will use [...document.getElementsByTagName('p')].forEach()
