### ISSUE TITLE
babel + core-js + webpack make code support old chrome, many node_modules file raise "export ... was not found" error

### ISSUE THREAD

**Issue by chikadance** [zloirock/core-js#999]
I reproduce err in [this project](https://drive.google.com/file/d/1Z1dV2bR3-0bIhb0MPdMzsFA7mAik0alO/view?usp=sharing)

following is my babel.config.js

    module.exports = {
        presets: [
            ["@babel/preset-env", {
                "useBuiltIns": "usage",
                "corejs": 3, // or 2,
                "targets": {
                    "chrome": "54" // babel is for debug, it make code compatible android webview, so compatible my genymotion android webview is enough
                },
                "exclude": ["@babel/plugin-transform-regenerator", "@babel/plugin-transform-arrow-functions"]
            }],
        ]
    }

when `npx webpack serve`, it raise many similar errs like `export 'default' (imported as 'stripAnsi') was not found in './modules/strip-ansi/index.js' (module has no exports)`

when babel.config.js set chrome:54, it raise err; when set chrome:74, not err, but I expect all code support chrome 54 **and I must use core-js to apply polyfill**, so how to fix this bug?

**Comment by gaplyk** [comment]
This issue related to core-js, it has a lot of cross references inside, so webpack can't resolve them. The nature of the issue is webpack replaces `require` function, which marks module loaded only when it's completely executed. But it doesn't happen, since eventually call to require will require the same script as at the beginning of chain and eventually will throw an error.

**Comment by zloirock** [comment]
@gaplyk `core-js` is used in most of popular websites. In most cases, it's bundled with `webpack`. Almost no one has this issue. The reason for such an issue is only incorrect usage. It's explained above - `core-js` should not be transpiled since some `babel` or `swc` transforms injects `core-js` to itself and those circular references can't be resolved.
